// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab_platform;

import "lab_platform/stable_version_key.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab_platform";


// FaftVersion is an association between a given ChromeOS version
// and a string uniquely identifying the faft firmware version.
// next tag: 3
message StableFaftVersion {
    StableVersionKey key = 1;
    string version = 2;
}
