// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab_platform;

import "lab_platform/stable_version_key.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab_platform";

// StableCrosVersion describes a ChromeOS version with a given stable version
// ID.
// next tag: 3
message StableCrosVersion {
    StableVersionKey key = 1;
    string version = 2;
}
