// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";
package chromite.api;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/chromite/api";

import "chromite/api/build_api.proto";
import "chromite/api/image.proto";
import "chromite/observability/sizes.proto";
import "chromiumos/common.proto";

message GetImageSizeDataRequest {
  repeated chromite.api.Image built_images = 1;
  chromiumos.Chroot chroot = 2;
}

message GetImageSizeDataResponse {
  repeated chromite.observability.ImageData image_data = 1;
}

service ObservabilityService {
  option (service_options) = {
    module : "observability",
    service_chroot_assert : INSIDE,
  };

  rpc GetImageSizeData(GetImageSizeDataRequest)
      returns (GetImageSizeDataResponse);
}
