// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.phosphorus;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/phosphorus";

// BotEnvironment defines bot-specific parameters used by phosphorus.
message BotEnvironment {
  // Absolute path to the autotest directory for the bot, e.g.
  // "/usr/local/autotest".
  string autotest_dir = 1;
}

// TaskEnvironment defines task-specific parameters used by phosphorus.
message TaskEnvironment {

  // Absolute path to the client offload directory, for high-reliability results
  string synchronous_offload_dir = 1;

  // Absolute path to the results directory for a given run.
  string results_dir = 2;
}

// Config defines configuration parameters common to phosphorus subcommands.
message Config {
  BotEnvironment bot = 1;
  TaskEnvironment task = 2;
}
