// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.phosphorus;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/phosphorus";

import "test_platform/phosphorus/common.proto";

// PrejobRequest defines the input of `phosphorus prejob`.
message PrejobRequest {
  Config config = 1;

  string dut_hostname = 2;

  map<string,string> provisionable_labels = 3 [deprecated = true];

  // What needs to be installed onto the DUT at the end of prejob, e.g.
  // "cros-version": "reef-release/R77-12345.0.0".
  map<string,string> desired_provisionable_labels = 4;

  // What is installed on the DUT before the prejob, e.g.
  // "cros-version": "reef-release/R77-12345.0.0".
  map<string,string> existing_provisionable_labels = 5;
}

