// Copyright 2019 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.phosphorus;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/phosphorus";

import "test_platform/phosphorus/common.proto";

// UploadToGSRequest defines the input of `phosphorus upload-to-gs`, for
// uploading to Google Storage.
message UploadToGSRequest {
  // Deprecated in favor of local_directory, which is the only thing it's used
  // for. Assembling that directory is moving to the 'callers'.
  Config config = 1 [ deprecated = true ];

  // GS path to upload to, e.g. gs://foo/bar/baz/
  string gs_directory = 2;

  reserved 3; // Task ID, was never used

  // Absolute path to local directory to upload to GS, e.g. /usr/local/foo/bar
  string local_directory = 4;
}

message UploadToGSResponse {
  // URL of Google Storage location containing offloaded files
  string gs_url = 1;
}
