syntax = "proto3";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/cycler/action.proto";

// Like it says on the tin.
message NoopActionConfiguration {};

message MoveActionConfiguration {

  // The destination bucket for the moved objects (e.g. 'engeg-testing-bucket').
  string destination_bucket = 1;

  // The destination prefix for the moved objects (e.g. moved-files-prefix).
  string destination_prefix = 2;

};

message CopyActionConfiguration {

  // The destination bucket for the copied objects (e.g. 'engeg-testing-bucket').
  string destination_bucket = 1;

  // The destination prefix for the copied objects (e.g. copied-files-prefix).
  string destination_prefix = 2;
};

message ChillActionConfiguration {};