// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.lucifer;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/lucifer";

import "test_platform/lucifer/common.proto";

// PrejobRequest defines the input of `lucifer prejob`.
message PrejobRequest {
  Config config = 1;

  string dut_hostname = 2;

  // What is currently installed on the DUT, e.g.
  // "cros-version": "reef-release/R77-12345.0.0".
  map<string,string> existing_provisionable_labels = 3;
}

