// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.steps;

import "chromite/api/test_metadata.proto";
import "test_platform/request.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/steps";

// EnumerationRequest defines the input of the test enumeration step.
message EnumerationRequest {
    test_platform.Request.Params.Metadata metadata = 1;
    test_platform.Request.TestPlan test_plan = 4;
}

// EnumerationResponse defines the output of the test enumeration step.
//
// This is copied in test_platform.Request.Enumeration
// Keep in sync.
message EnumerationResponse {
    message AutotestInvocation {
        chromite.api.AutotestTest test = 1;

        // Passthrough arguments from test_platform.Request_Test
        string test_args = 2;
        string display_name = 3;
    }

    repeated AutotestInvocation autotest_invocations = 2;
}
