// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.steps;

import "chromite/api/test_metadata.proto";
import "test_platform/request.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/steps";

// EnumerationRequest defines the input of the test enumeration step.
message EnumerationRequest {
    test_platform.Request.Params.Metadata metadata = 1;
    repeated test_platform.Request.Suite suites = 2;
    repeated test_platform.Request.Test tests = 3;
}

// EnumerationResponse defines the output of the test enumeration step.
message EnumerationResponse {
    repeated chromite.api.AutotestTest autotest_tests = 1;
}
