// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.steps;

import "test_platform/request.proto";
import "test_platform/steps/enumeration.proto";
import "test_platform/config/config.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/steps";

// ExecuteRequest defines the input of the Execute step.
message ExecuteRequest {
    // Request is the full cros_test_platform request.
    //
    // TODO(akeshet): Don't expose the full request to the enumeration step,
    // pull out only the fields that it needs.
    test_platform.Request request = 1;

    EnumerationResponse enumeration = 2;

    test_platform.config.Config config = 3;
}

// ExecuteResponse defines the output of the Execute step.
message ExecuteResponse {
    message TaskResult {
        string task_id = 1;

        string task_url = 2;

        enum TaskStatus {
            TASK_STATUS_UNSPECIFIED = 0;
            // TODO(akeshet): Add statuses.
        }

        TaskStatus status = 3;

        string name = 4;
    }

    repeated TaskResult task_results = 1;
}
