// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.steps;

import "test_platform/request.proto";
import "test_platform/steps/enumeration.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/steps";

// SelectorRequest defines the input of the backend selector step.
message SelectorRequest {
    // Request is the full cros_test_platform request.
    //
    // TODO(akeshet): Don't expose the full request to the enumeration step,
    // pull out only the fields that it needs.
    test_platform.Request request = 1;

    EnumerationResponse enumeration = 2;
}

// SelectorResponse defines the output of the test enumeration step.
message SelectorResponse {
    enum Backend {
        BACKEND_UNSPECIFIED = 0;
        BACKEND_AUTOTEST = 1;
        BACKEND_SKYLAB = 2;
    }

    Backend backend = 1;
}
