// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/builder_config.proto

package chromiumos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Used to control running of special steps.
type BuilderConfig_RunSpec int32

const (
	BuilderConfig_RUN_SPEC_UNSPECIFIED BuilderConfig_RunSpec = 0
	// Do not run.
	BuilderConfig_NO_RUN BuilderConfig_RunSpec = 1
	// Run.
	BuilderConfig_RUN BuilderConfig_RunSpec = 2
	// Run and then exit.
	BuilderConfig_RUN_EXIT BuilderConfig_RunSpec = 3
)

var BuilderConfig_RunSpec_name = map[int32]string{
	0: "RUN_SPEC_UNSPECIFIED",
	1: "NO_RUN",
	2: "RUN",
	3: "RUN_EXIT",
}

var BuilderConfig_RunSpec_value = map[string]int32{
	"RUN_SPEC_UNSPECIFIED": 0,
	"NO_RUN":               1,
	"RUN":                  2,
	"RUN_EXIT":             3,
}

func (x BuilderConfig_RunSpec) String() string {
	return proto.EnumName(BuilderConfig_RunSpec_name, int32(x))
}

func (BuilderConfig_RunSpec) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 0}
}

// Type of build.
type BuilderConfig_Id_Type int32

const (
	BuilderConfig_Id_TYPE_UNSPECIFIED BuilderConfig_Id_Type = 0
	// Commit queue build.
	BuilderConfig_Id_CQ BuilderConfig_Id_Type = 1
	// Postsubmit build.
	BuilderConfig_Id_POSTSUBMIT BuilderConfig_Id_Type = 2
	// Toolchain build.
	BuilderConfig_Id_TOOLCHAIN BuilderConfig_Id_Type = 3
)

var BuilderConfig_Id_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "CQ",
	2: "POSTSUBMIT",
	3: "TOOLCHAIN",
}

var BuilderConfig_Id_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"CQ":               1,
	"POSTSUBMIT":       2,
	"TOOLCHAIN":        3,
}

func (x BuilderConfig_Id_Type) String() string {
	return proto.EnumName(BuilderConfig_Id_Type_name, int32(x))
}

func (BuilderConfig_Id_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 0, 0}
}

type BuilderConfig_General_Environment int32

const (
	BuilderConfig_General_ENVIRONMENT_UNSPECIFIED BuilderConfig_General_Environment = 0
	BuilderConfig_General_PRODUCTION              BuilderConfig_General_Environment = 1
	BuilderConfig_General_STAGING                 BuilderConfig_General_Environment = 2
)

var BuilderConfig_General_Environment_name = map[int32]string{
	0: "ENVIRONMENT_UNSPECIFIED",
	1: "PRODUCTION",
	2: "STAGING",
}

var BuilderConfig_General_Environment_value = map[string]int32{
	"ENVIRONMENT_UNSPECIFIED": 0,
	"PRODUCTION":              1,
	"STAGING":                 2,
}

func (x BuilderConfig_General_Environment) String() string {
	return proto.EnumName(BuilderConfig_General_Environment_name, int32(x))
}

func (BuilderConfig_General_Environment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 1, 0}
}

type BuilderConfig_General_RunWhen_Mode int32

const (
	BuilderConfig_General_RunWhen_MODE_UNSPECIFIED BuilderConfig_General_RunWhen_Mode = 0
	// Always run this builder. The file_patterns field will be ignored
	// when this mode is selected.
	BuilderConfig_General_RunWhen_ALWAYS_RUN BuilderConfig_General_RunWhen_Mode = 1
	// Only run this builder if any file in the input gerrit_changes
	// matches any file_pattern specified below. If file_patterns is empty,
	// this option implies the builder will never run.
	BuilderConfig_General_RunWhen_ONLY_RUN_ON_FILE_MATCH BuilderConfig_General_RunWhen_Mode = 2
	// Do not run the builder if all files in the input gerrit_changes
	// match any file_attern speicifed below. If file_patterns is empty,
	// this option implies the builder will always run.
	BuilderConfig_General_RunWhen_NO_RUN_ON_FILE_MATCH BuilderConfig_General_RunWhen_Mode = 3
)

var BuilderConfig_General_RunWhen_Mode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	1: "ALWAYS_RUN",
	2: "ONLY_RUN_ON_FILE_MATCH",
	3: "NO_RUN_ON_FILE_MATCH",
}

var BuilderConfig_General_RunWhen_Mode_value = map[string]int32{
	"MODE_UNSPECIFIED":       0,
	"ALWAYS_RUN":             1,
	"ONLY_RUN_ON_FILE_MATCH": 2,
	"NO_RUN_ON_FILE_MATCH":   3,
}

func (x BuilderConfig_General_RunWhen_Mode) String() string {
	return proto.EnumName(BuilderConfig_General_RunWhen_Mode_name, int32(x))
}

func (BuilderConfig_General_RunWhen_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 1, 0, 0}
}

// How to handle the uploading of prebuilts.
type BuilderConfig_Artifacts_Prebuilts int32

const (
	BuilderConfig_Artifacts_PREBUILTS_UNSPECIFIED BuilderConfig_Artifacts_Prebuilts = 0
	BuilderConfig_Artifacts_PUBLIC                BuilderConfig_Artifacts_Prebuilts = 1
	BuilderConfig_Artifacts_PRIVATE               BuilderConfig_Artifacts_Prebuilts = 2
	BuilderConfig_Artifacts_NONE                  BuilderConfig_Artifacts_Prebuilts = 3
)

var BuilderConfig_Artifacts_Prebuilts_name = map[int32]string{
	0: "PREBUILTS_UNSPECIFIED",
	1: "PUBLIC",
	2: "PRIVATE",
	3: "NONE",
}

var BuilderConfig_Artifacts_Prebuilts_value = map[string]int32{
	"PREBUILTS_UNSPECIFIED": 0,
	"PUBLIC":                1,
	"PRIVATE":               2,
	"NONE":                  3,
}

func (x BuilderConfig_Artifacts_Prebuilts) String() string {
	return proto.EnumName(BuilderConfig_Artifacts_Prebuilts_name, int32(x))
}

func (BuilderConfig_Artifacts_Prebuilts) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3, 0}
}

// Used to indicate artifact types that should be uploaded by the builder.
// Must be kept in sync with the dictionary in:
// https://chromium.googlesource.com/chromiumos/infra/recipes/+/refs/heads/master/recipe_modules/cros_artifacts/api.py
type BuilderConfig_Artifacts_ArtifactTypes int32

const (
	BuilderConfig_Artifacts_ARTIFACT_TYPES_UNSPECIFIED BuilderConfig_Artifacts_ArtifactTypes = 0
	// Indicates wanting a zip file of everything in the image directory.
	BuilderConfig_Artifacts_IMAGE_ZIP BuilderConfig_Artifacts_ArtifactTypes = 1
	// Indicates wanting update payloads.
	BuilderConfig_Artifacts_TEST_UPDATE_PAYLOAD BuilderConfig_Artifacts_ArtifactTypes = 2
	// Indicates wanting the autotest tarballs.
	BuilderConfig_Artifacts_AUTOTEST_FILES BuilderConfig_Artifacts_ArtifactTypes = 3
	// Indicates wanting a tarball containing private TAST test bundles.
	BuilderConfig_Artifacts_TAST_FILES BuilderConfig_Artifacts_ArtifactTypes = 4
	// Indicates wanting a tarball containing guest images and test bundles.
	BuilderConfig_Artifacts_PINNED_GUEST_IMAGES BuilderConfig_Artifacts_ArtifactTypes = 5
	// Indicates wanting an archive of firmware images built from source.
	BuilderConfig_Artifacts_FIRMWARE BuilderConfig_Artifacts_ArtifactTypes = 6
	// Indicates wanting a tarball of the Ebuilds logs.
	BuilderConfig_Artifacts_EBUILD_LOGS BuilderConfig_Artifacts_ArtifactTypes = 7
	// Indicates wanting an archive of the ChromeOS Config.
	BuilderConfig_Artifacts_CHROMEOS_CONFIG BuilderConfig_Artifacts_ArtifactTypes = 8
	// Indicates wanting the CPE report.
	BuilderConfig_Artifacts_CPE_REPORT BuilderConfig_Artifacts_ArtifactTypes = 9
	// Indicates wanting a tar.xz archive for each image that has been created.
	BuilderConfig_Artifacts_IMAGE_ARCHIVES BuilderConfig_Artifacts_ArtifactTypes = 10
	//
	// Artifacts from ORDERFILE_GENERATE through KERNEL_AFDO_VERIFY are used
	// by the toolchain.
	//
	// Indicates wanting an unvetted orderfile for Chrome.
	BuilderConfig_Artifacts_UNVERIFIED_ORDERING_FILE BuilderConfig_Artifacts_ArtifactTypes = 11
	// Indicates wanting a vetted orderfile for Chrome.
	BuilderConfig_Artifacts_VERIFIED_ORDERING_FILE BuilderConfig_Artifacts_ArtifactTypes = 12
	// Indicates wanting a clang-tidy artifact.
	BuilderConfig_Artifacts_CHROME_CLANG_WARNINGS_FILE BuilderConfig_Artifacts_ArtifactTypes = 13
	// Indicates wanting a PGO artifact for the compiler.
	BuilderConfig_Artifacts_UNVERIFIED_LLVM_PGO_FILE BuilderConfig_Artifacts_ArtifactTypes = 14
	// Indicates wanting an unvetted AFDO Chrome profile.
	BuilderConfig_Artifacts_UNVERIFIED_CHROME_AFDO_FILE BuilderConfig_Artifacts_ArtifactTypes = 15
	// Indicates wanting a vetted AFDO Chrome profile.
	BuilderConfig_Artifacts_VERIFIED_CHROME_AFDO_FILE BuilderConfig_Artifacts_ArtifactTypes = 16
	// Indicates wanting a vetted AFDO Kernel profile.
	BuilderConfig_Artifacts_VERIFIED_KERNEL_AFDO_FILE BuilderConfig_Artifacts_ArtifactTypes = 17
)

var BuilderConfig_Artifacts_ArtifactTypes_name = map[int32]string{
	0:  "ARTIFACT_TYPES_UNSPECIFIED",
	1:  "IMAGE_ZIP",
	2:  "TEST_UPDATE_PAYLOAD",
	3:  "AUTOTEST_FILES",
	4:  "TAST_FILES",
	5:  "PINNED_GUEST_IMAGES",
	6:  "FIRMWARE",
	7:  "EBUILD_LOGS",
	8:  "CHROMEOS_CONFIG",
	9:  "CPE_REPORT",
	10: "IMAGE_ARCHIVES",
	11: "UNVERIFIED_ORDERING_FILE",
	12: "VERIFIED_ORDERING_FILE",
	13: "CHROME_CLANG_WARNINGS_FILE",
	14: "UNVERIFIED_LLVM_PGO_FILE",
	15: "UNVERIFIED_CHROME_AFDO_FILE",
	16: "VERIFIED_CHROME_AFDO_FILE",
	17: "VERIFIED_KERNEL_AFDO_FILE",
}

var BuilderConfig_Artifacts_ArtifactTypes_value = map[string]int32{
	"ARTIFACT_TYPES_UNSPECIFIED":  0,
	"IMAGE_ZIP":                   1,
	"TEST_UPDATE_PAYLOAD":         2,
	"AUTOTEST_FILES":              3,
	"TAST_FILES":                  4,
	"PINNED_GUEST_IMAGES":         5,
	"FIRMWARE":                    6,
	"EBUILD_LOGS":                 7,
	"CHROMEOS_CONFIG":             8,
	"CPE_REPORT":                  9,
	"IMAGE_ARCHIVES":              10,
	"UNVERIFIED_ORDERING_FILE":    11,
	"VERIFIED_ORDERING_FILE":      12,
	"CHROME_CLANG_WARNINGS_FILE":  13,
	"UNVERIFIED_LLVM_PGO_FILE":    14,
	"UNVERIFIED_CHROME_AFDO_FILE": 15,
	"VERIFIED_CHROME_AFDO_FILE":   16,
	"VERIFIED_KERNEL_AFDO_FILE":   17,
}

func (x BuilderConfig_Artifacts_ArtifactTypes) String() string {
	return proto.EnumName(BuilderConfig_Artifacts_ArtifactTypes_name, int32(x))
}

func (BuilderConfig_Artifacts_ArtifactTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3, 1}
}

// Configuration used by a builder during execution.
type BuilderConfig struct {
	Id                   *BuilderConfig_Id           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	General              *BuilderConfig_General      `protobuf:"bytes,2,opt,name=general,proto3" json:"general,omitempty"`
	Orchestrator         *BuilderConfig_Orchestrator `protobuf:"bytes,3,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"`
	Artifacts            *BuilderConfig_Artifacts    `protobuf:"bytes,4,opt,name=artifacts,proto3" json:"artifacts,omitempty"`
	Chrome               *BuilderConfig_Chrome       `protobuf:"bytes,5,opt,name=chrome,proto3" json:"chrome,omitempty"`
	Build                *BuilderConfig_Build        `protobuf:"bytes,6,opt,name=build,proto3" json:"build,omitempty"`
	UnitTests            *BuilderConfig_UnitTests    `protobuf:"bytes,7,opt,name=unit_tests,json=unitTests,proto3" json:"unit_tests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BuilderConfig) Reset()         { *m = BuilderConfig{} }
func (m *BuilderConfig) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig) ProtoMessage()    {}
func (*BuilderConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0}
}

func (m *BuilderConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig.Unmarshal(m, b)
}
func (m *BuilderConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig.Marshal(b, m, deterministic)
}
func (m *BuilderConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig.Merge(m, src)
}
func (m *BuilderConfig) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig.Size(m)
}
func (m *BuilderConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig proto.InternalMessageInfo

func (m *BuilderConfig) GetId() *BuilderConfig_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BuilderConfig) GetGeneral() *BuilderConfig_General {
	if m != nil {
		return m.General
	}
	return nil
}

func (m *BuilderConfig) GetOrchestrator() *BuilderConfig_Orchestrator {
	if m != nil {
		return m.Orchestrator
	}
	return nil
}

func (m *BuilderConfig) GetArtifacts() *BuilderConfig_Artifacts {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *BuilderConfig) GetChrome() *BuilderConfig_Chrome {
	if m != nil {
		return m.Chrome
	}
	return nil
}

func (m *BuilderConfig) GetBuild() *BuilderConfig_Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *BuilderConfig) GetUnitTests() *BuilderConfig_UnitTests {
	if m != nil {
		return m.UnitTests
	}
	return nil
}

// Unique identifier of the builder configuration.
type BuilderConfig_Id struct {
	// The name of the configuration such as "arm-generic-postsubmit".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Branch the configuration applies to such as "release-R73-11647.B".
	Branch               string                `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Type                 BuilderConfig_Id_Type `protobuf:"varint,3,opt,name=type,proto3,enum=chromiumos.BuilderConfig_Id_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BuilderConfig_Id) Reset()         { *m = BuilderConfig_Id{} }
func (m *BuilderConfig_Id) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Id) ProtoMessage()    {}
func (*BuilderConfig_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 0}
}

func (m *BuilderConfig_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Id.Unmarshal(m, b)
}
func (m *BuilderConfig_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Id.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Id.Merge(m, src)
}
func (m *BuilderConfig_Id) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Id.Size(m)
}
func (m *BuilderConfig_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Id.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Id proto.InternalMessageInfo

func (m *BuilderConfig_Id) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuilderConfig_Id) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuilderConfig_Id) GetType() BuilderConfig_Id_Type {
	if m != nil {
		return m.Type
	}
	return BuilderConfig_Id_TYPE_UNSPECIFIED
}

// General configuration for the builder.
type BuilderConfig_General struct {
	// Whether or not the build is considered critical. A failure in a critical
	// build for a CQ builder may, for example, prevent submission of the CL.
	Critical    *wrappers.BoolValue               `protobuf:"bytes,1,opt,name=critical,proto3" json:"critical,omitempty"`
	Environment BuilderConfig_General_Environment `protobuf:"varint,2,opt,name=environment,proto3,enum=chromiumos.BuilderConfig_General_Environment" json:"environment,omitempty"`
	// A rule describing conditions under which this builder should be launched.
	RunWhen *BuilderConfig_General_RunWhen `protobuf:"bytes,3,opt,name=run_when,json=runWhen,proto3" json:"run_when,omitempty"`
	// Time before which ToT had a bug that would not manifest at the
	// build stage. The CQ orchestrator should NOT reuse successful builds
	// of the build_config before this.
	BrokenBefore         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=broken_before,json=brokenBefore,proto3" json:"broken_before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuilderConfig_General) Reset()         { *m = BuilderConfig_General{} }
func (m *BuilderConfig_General) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_General) ProtoMessage()    {}
func (*BuilderConfig_General) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 1}
}

func (m *BuilderConfig_General) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_General.Unmarshal(m, b)
}
func (m *BuilderConfig_General) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_General.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_General) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_General.Merge(m, src)
}
func (m *BuilderConfig_General) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_General.Size(m)
}
func (m *BuilderConfig_General) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_General.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_General proto.InternalMessageInfo

func (m *BuilderConfig_General) GetCritical() *wrappers.BoolValue {
	if m != nil {
		return m.Critical
	}
	return nil
}

func (m *BuilderConfig_General) GetEnvironment() BuilderConfig_General_Environment {
	if m != nil {
		return m.Environment
	}
	return BuilderConfig_General_ENVIRONMENT_UNSPECIFIED
}

func (m *BuilderConfig_General) GetRunWhen() *BuilderConfig_General_RunWhen {
	if m != nil {
		return m.RunWhen
	}
	return nil
}

func (m *BuilderConfig_General) GetBrokenBefore() *timestamp.Timestamp {
	if m != nil {
		return m.BrokenBefore
	}
	return nil
}

// Rule describing conditions under which a builder should be launched.
type BuilderConfig_General_RunWhen struct {
	Mode BuilderConfig_General_RunWhen_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=chromiumos.BuilderConfig_General_RunWhen_Mode" json:"mode,omitempty"`
	// chromiumos code file patterns, relative to chromiumos root, which may
	// use * or ** for globbing.
	// e.g.
	// chromite/myfile.txt
	// chromite/config/*
	// **/*.md
	FilePatterns         []string `protobuf:"bytes,2,rep,name=file_patterns,json=filePatterns,proto3" json:"file_patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_General_RunWhen) Reset()         { *m = BuilderConfig_General_RunWhen{} }
func (m *BuilderConfig_General_RunWhen) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_General_RunWhen) ProtoMessage()    {}
func (*BuilderConfig_General_RunWhen) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 1, 0}
}

func (m *BuilderConfig_General_RunWhen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_General_RunWhen.Unmarshal(m, b)
}
func (m *BuilderConfig_General_RunWhen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_General_RunWhen.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_General_RunWhen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_General_RunWhen.Merge(m, src)
}
func (m *BuilderConfig_General_RunWhen) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_General_RunWhen.Size(m)
}
func (m *BuilderConfig_General_RunWhen) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_General_RunWhen.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_General_RunWhen proto.InternalMessageInfo

func (m *BuilderConfig_General_RunWhen) GetMode() BuilderConfig_General_RunWhen_Mode {
	if m != nil {
		return m.Mode
	}
	return BuilderConfig_General_RunWhen_MODE_UNSPECIFIED
}

func (m *BuilderConfig_General_RunWhen) GetFilePatterns() []string {
	if m != nil {
		return m.FilePatterns
	}
	return nil
}

// Configuration pertaining to builders operating as "orchestrators".
// Orchestrators orchestrate the running of other child builders.
type BuilderConfig_Orchestrator struct {
	// BuilderConfig.Id.name of the child builds. They would expect to match
	// this name and the BuilderConfig.Id.branch and BuilderConfig.Id.type of
	// this parent orchestrator builder.
	Children []string `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	// GitilesCommit to use if not provided.
	GitilesCommit        *GitilesCommit                                   `protobuf:"bytes,2,opt,name=gitiles_commit,json=gitilesCommit,proto3" json:"gitiles_commit,omitempty"`
	FollowOnOrchestrator *BuilderConfig_Orchestrator_FollowOnOrchestrator `protobuf:"bytes,3,opt,name=follow_on_orchestrator,json=followOnOrchestrator,proto3" json:"follow_on_orchestrator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *BuilderConfig_Orchestrator) Reset()         { *m = BuilderConfig_Orchestrator{} }
func (m *BuilderConfig_Orchestrator) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Orchestrator) ProtoMessage()    {}
func (*BuilderConfig_Orchestrator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 2}
}

func (m *BuilderConfig_Orchestrator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Unmarshal(m, b)
}
func (m *BuilderConfig_Orchestrator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Orchestrator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Orchestrator.Merge(m, src)
}
func (m *BuilderConfig_Orchestrator) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Size(m)
}
func (m *BuilderConfig_Orchestrator) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Orchestrator.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Orchestrator proto.InternalMessageInfo

func (m *BuilderConfig_Orchestrator) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *BuilderConfig_Orchestrator) GetGitilesCommit() *GitilesCommit {
	if m != nil {
		return m.GitilesCommit
	}
	return nil
}

func (m *BuilderConfig_Orchestrator) GetFollowOnOrchestrator() *BuilderConfig_Orchestrator_FollowOnOrchestrator {
	if m != nil {
		return m.FollowOnOrchestrator
	}
	return nil
}

// Follow on orchestrator to launch, and possibly wait for.
type BuilderConfig_Orchestrator_FollowOnOrchestrator struct {
	// BuilderConfig.Id.name of the follow on orchestrator.
	FollowOnOrchestrator string `protobuf:"bytes,1,opt,name=follow_on_orchestrator,json=followOnOrchestrator,proto3" json:"follow_on_orchestrator,omitempty"`
	// Whether to wait for the follow on orchestrator to finish.
	WaitForFollowOn      bool     `protobuf:"varint,2,opt,name=wait_for_follow_on,json=waitForFollowOn,proto3" json:"wait_for_follow_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) Reset() {
	*m = BuilderConfig_Orchestrator_FollowOnOrchestrator{}
}
func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) String() string {
	return proto.CompactTextString(m)
}
func (*BuilderConfig_Orchestrator_FollowOnOrchestrator) ProtoMessage() {}
func (*BuilderConfig_Orchestrator_FollowOnOrchestrator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 2, 0}
}

func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator.Unmarshal(m, b)
}
func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator.Merge(m, src)
}
func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator.Size(m)
}
func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Orchestrator_FollowOnOrchestrator proto.InternalMessageInfo

func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) GetFollowOnOrchestrator() string {
	if m != nil {
		return m.FollowOnOrchestrator
	}
	return ""
}

func (m *BuilderConfig_Orchestrator_FollowOnOrchestrator) GetWaitForFollowOn() bool {
	if m != nil {
		return m.WaitForFollowOn
	}
	return false
}

// Configuration pertaining to artifacts produced during a build.
type BuilderConfig_Artifacts struct {
	Prebuilts     BuilderConfig_Artifacts_Prebuilts       `protobuf:"varint,1,opt,name=prebuilts,proto3,enum=chromiumos.BuilderConfig_Artifacts_Prebuilts" json:"prebuilts,omitempty"`
	ArtifactTypes []BuilderConfig_Artifacts_ArtifactTypes `protobuf:"varint,2,rep,packed,name=artifact_types,json=artifactTypes,proto3,enum=chromiumos.BuilderConfig_Artifacts_ArtifactTypes" json:"artifact_types,omitempty"`
	// Google storage bucket to upload prebuilts to.
	PrebuiltsGsBucket string `protobuf:"bytes,3,opt,name=prebuilts_gs_bucket,json=prebuiltsGsBucket,proto3" json:"prebuilts_gs_bucket,omitempty"`
	// Google storage bucket to upload artifacts to.
	ArtifactsGsBucket string `protobuf:"bytes,4,opt,name=artifacts_gs_bucket,json=artifactsGsBucket,proto3" json:"artifacts_gs_bucket,omitempty"`
	// There may be more than one set of publishing instructions.
	PublishArtifacts     []*BuilderConfig_Artifacts_PublishInfo `protobuf:"bytes,5,rep,name=publish_artifacts,json=publishArtifacts,proto3" json:"publish_artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *BuilderConfig_Artifacts) Reset()         { *m = BuilderConfig_Artifacts{} }
func (m *BuilderConfig_Artifacts) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Artifacts) ProtoMessage()    {}
func (*BuilderConfig_Artifacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3}
}

func (m *BuilderConfig_Artifacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Artifacts.Unmarshal(m, b)
}
func (m *BuilderConfig_Artifacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Artifacts.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Artifacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Artifacts.Merge(m, src)
}
func (m *BuilderConfig_Artifacts) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Artifacts.Size(m)
}
func (m *BuilderConfig_Artifacts) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Artifacts.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Artifacts proto.InternalMessageInfo

func (m *BuilderConfig_Artifacts) GetPrebuilts() BuilderConfig_Artifacts_Prebuilts {
	if m != nil {
		return m.Prebuilts
	}
	return BuilderConfig_Artifacts_PREBUILTS_UNSPECIFIED
}

func (m *BuilderConfig_Artifacts) GetArtifactTypes() []BuilderConfig_Artifacts_ArtifactTypes {
	if m != nil {
		return m.ArtifactTypes
	}
	return nil
}

func (m *BuilderConfig_Artifacts) GetPrebuiltsGsBucket() string {
	if m != nil {
		return m.PrebuiltsGsBucket
	}
	return ""
}

func (m *BuilderConfig_Artifacts) GetArtifactsGsBucket() string {
	if m != nil {
		return m.ArtifactsGsBucket
	}
	return ""
}

func (m *BuilderConfig_Artifacts) GetPublishArtifacts() []*BuilderConfig_Artifacts_PublishInfo {
	if m != nil {
		return m.PublishArtifacts
	}
	return nil
}

type BuilderConfig_Artifacts_PublishInfo struct {
	// Google storage bucket to publish these artifact types to.
	PublishGsBucket string `protobuf:"bytes,1,opt,name=publish_gs_bucket,json=publishGsBucket,proto3" json:"publish_gs_bucket,omitempty"`
	// Artifact types to publish to this bucket.
	PublishTypes         []BuilderConfig_Artifacts_ArtifactTypes `protobuf:"varint,2,rep,packed,name=publish_types,json=publishTypes,proto3,enum=chromiumos.BuilderConfig_Artifacts_ArtifactTypes" json:"publish_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *BuilderConfig_Artifacts_PublishInfo) Reset()         { *m = BuilderConfig_Artifacts_PublishInfo{} }
func (m *BuilderConfig_Artifacts_PublishInfo) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Artifacts_PublishInfo) ProtoMessage()    {}
func (*BuilderConfig_Artifacts_PublishInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3, 0}
}

func (m *BuilderConfig_Artifacts_PublishInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo.Unmarshal(m, b)
}
func (m *BuilderConfig_Artifacts_PublishInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Artifacts_PublishInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo.Merge(m, src)
}
func (m *BuilderConfig_Artifacts_PublishInfo) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo.Size(m)
}
func (m *BuilderConfig_Artifacts_PublishInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Artifacts_PublishInfo proto.InternalMessageInfo

func (m *BuilderConfig_Artifacts_PublishInfo) GetPublishGsBucket() string {
	if m != nil {
		return m.PublishGsBucket
	}
	return ""
}

func (m *BuilderConfig_Artifacts_PublishInfo) GetPublishTypes() []BuilderConfig_Artifacts_ArtifactTypes {
	if m != nil {
		return m.PublishTypes
	}
	return nil
}

// Configuration pertaining to Chrome.
type BuilderConfig_Chrome struct {
	// Whether to build internal or external Chrome. Internal chrome adds
	// Chrome branding.
	Internal             bool     `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Chrome) Reset()         { *m = BuilderConfig_Chrome{} }
func (m *BuilderConfig_Chrome) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Chrome) ProtoMessage()    {}
func (*BuilderConfig_Chrome) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 4}
}

func (m *BuilderConfig_Chrome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Chrome.Unmarshal(m, b)
}
func (m *BuilderConfig_Chrome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Chrome.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Chrome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Chrome.Merge(m, src)
}
func (m *BuilderConfig_Chrome) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Chrome.Size(m)
}
func (m *BuilderConfig_Chrome) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Chrome.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Chrome proto.InternalMessageInfo

func (m *BuilderConfig_Chrome) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

// Build specific configuration.
type BuilderConfig_Build struct {
	// USE flags to use with the build.
	UseFlags       []*UseFlag                          `protobuf:"bytes,1,rep,name=use_flags,json=useFlags,proto3" json:"use_flags,omitempty"`
	PortageProfile *BuilderConfig_Build_PortageProfile `protobuf:"bytes,2,opt,name=portage_profile,json=portageProfile,proto3" json:"portage_profile,omitempty"`
	// Image types to build.
	ImageTypes []ImageType `protobuf:"varint,3,rep,packed,name=image_types,json=imageTypes,proto3,enum=chromiumos.ImageType" json:"image_types,omitempty"`
	// Controls the running of the install packages step.
	InstallPackages BuilderConfig_RunSpec `protobuf:"varint,4,opt,name=install_packages,json=installPackages,proto3,enum=chromiumos.BuilderConfig_RunSpec" json:"install_packages,omitempty"`
	// Compile toolchain from source (true), or use bin packages (false).
	CompileToolchain bool `protobuf:"varint,5,opt,name=compile_toolchain,json=compileToolchain,proto3" json:"compile_toolchain,omitempty"`
	// Whether to apply gerrit changes, if any. Use case is to build without
	// changes after failure to identify the changes as the culprit.
	ApplyGerritChanges bool `protobuf:"varint,6,opt,name=apply_gerrit_changes,json=applyGerritChanges,proto3" json:"apply_gerrit_changes,omitempty"`
	// Packages to build, or empty to build all packages.
	Packages       []*PackageInfo                       `protobuf:"bytes,7,rep,name=packages,proto3" json:"packages,omitempty"`
	ToolchainSteps []*BuilderConfig_Build_ToolchainStep `protobuf:"bytes,8,rep,name=toolchain_steps,json=toolchainSteps,proto3" json:"toolchain_steps,omitempty"`
	// Build packages from source.
	CompileSource        bool     `protobuf:"varint,10,opt,name=compile_source,json=compileSource,proto3" json:"compile_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Build) Reset()         { *m = BuilderConfig_Build{} }
func (m *BuilderConfig_Build) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Build) ProtoMessage()    {}
func (*BuilderConfig_Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 5}
}

func (m *BuilderConfig_Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Build.Unmarshal(m, b)
}
func (m *BuilderConfig_Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Build.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Build.Merge(m, src)
}
func (m *BuilderConfig_Build) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Build.Size(m)
}
func (m *BuilderConfig_Build) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Build.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Build proto.InternalMessageInfo

func (m *BuilderConfig_Build) GetUseFlags() []*UseFlag {
	if m != nil {
		return m.UseFlags
	}
	return nil
}

func (m *BuilderConfig_Build) GetPortageProfile() *BuilderConfig_Build_PortageProfile {
	if m != nil {
		return m.PortageProfile
	}
	return nil
}

func (m *BuilderConfig_Build) GetImageTypes() []ImageType {
	if m != nil {
		return m.ImageTypes
	}
	return nil
}

func (m *BuilderConfig_Build) GetInstallPackages() BuilderConfig_RunSpec {
	if m != nil {
		return m.InstallPackages
	}
	return BuilderConfig_RUN_SPEC_UNSPECIFIED
}

func (m *BuilderConfig_Build) GetCompileToolchain() bool {
	if m != nil {
		return m.CompileToolchain
	}
	return false
}

func (m *BuilderConfig_Build) GetApplyGerritChanges() bool {
	if m != nil {
		return m.ApplyGerritChanges
	}
	return false
}

func (m *BuilderConfig_Build) GetPackages() []*PackageInfo {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *BuilderConfig_Build) GetToolchainSteps() []*BuilderConfig_Build_ToolchainStep {
	if m != nil {
		return m.ToolchainSteps
	}
	return nil
}

func (m *BuilderConfig_Build) GetCompileSource() bool {
	if m != nil {
		return m.CompileSource
	}
	return false
}

// The profile of the variant to set up and build.
type BuilderConfig_Build_PortageProfile struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Build_PortageProfile) Reset()         { *m = BuilderConfig_Build_PortageProfile{} }
func (m *BuilderConfig_Build_PortageProfile) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Build_PortageProfile) ProtoMessage()    {}
func (*BuilderConfig_Build_PortageProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 5, 0}
}

func (m *BuilderConfig_Build_PortageProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Build_PortageProfile.Unmarshal(m, b)
}
func (m *BuilderConfig_Build_PortageProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Build_PortageProfile.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Build_PortageProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Build_PortageProfile.Merge(m, src)
}
func (m *BuilderConfig_Build_PortageProfile) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Build_PortageProfile.Size(m)
}
func (m *BuilderConfig_Build_PortageProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Build_PortageProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Build_PortageProfile proto.InternalMessageInfo

func (m *BuilderConfig_Build_PortageProfile) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

// Used to insert steps into the build for toolchain optimizations.
// DEPRECATED. crbug/1019868.  This message was added as an experiment, and
// will be removed as soon as the code using it has been removed from
// configs and recipes.
type BuilderConfig_Build_ToolchainStep struct {
	// AFDO_artifact types generated by this build.
	GenerateArtifactTypes []AFDOArtifactType `protobuf:"varint,1,rep,packed,name=generate_artifact_types,json=generateArtifactTypes,proto3,enum=chromiumos.AFDOArtifactType" json:"generate_artifact_types,omitempty"`
	// AFDO_artifact types verified by this build.
	VerifyArtifactTypes  []AFDOArtifactType `protobuf:"varint,2,rep,packed,name=verify_artifact_types,json=verifyArtifactTypes,proto3,enum=chromiumos.AFDOArtifactType" json:"verify_artifact_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BuilderConfig_Build_ToolchainStep) Reset()         { *m = BuilderConfig_Build_ToolchainStep{} }
func (m *BuilderConfig_Build_ToolchainStep) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Build_ToolchainStep) ProtoMessage()    {}
func (*BuilderConfig_Build_ToolchainStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 5, 1}
}

func (m *BuilderConfig_Build_ToolchainStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Build_ToolchainStep.Unmarshal(m, b)
}
func (m *BuilderConfig_Build_ToolchainStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Build_ToolchainStep.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Build_ToolchainStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Build_ToolchainStep.Merge(m, src)
}
func (m *BuilderConfig_Build_ToolchainStep) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Build_ToolchainStep.Size(m)
}
func (m *BuilderConfig_Build_ToolchainStep) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Build_ToolchainStep.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Build_ToolchainStep proto.InternalMessageInfo

func (m *BuilderConfig_Build_ToolchainStep) GetGenerateArtifactTypes() []AFDOArtifactType {
	if m != nil {
		return m.GenerateArtifactTypes
	}
	return nil
}

func (m *BuilderConfig_Build_ToolchainStep) GetVerifyArtifactTypes() []AFDOArtifactType {
	if m != nil {
		return m.VerifyArtifactTypes
	}
	return nil
}

type BuilderConfig_UnitTests struct {
	// Skipped packages.
	PackageBlacklist []*PackageInfo `protobuf:"bytes,4,rep,name=package_blacklist,json=packageBlacklist,proto3" json:"package_blacklist,omitempty"`
	// Controls the running of ebuild tests with possible early exit.
	EbuildsRunSpec BuilderConfig_RunSpec `protobuf:"varint,5,opt,name=ebuilds_run_spec,json=ebuildsRunSpec,proto3,enum=chromiumos.BuilderConfig_RunSpec" json:"ebuilds_run_spec,omitempty"`
	// Whether to assume the sysroot is empty.
	EmptySysroot         bool     `protobuf:"varint,6,opt,name=empty_sysroot,json=emptySysroot,proto3" json:"empty_sysroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_UnitTests) Reset()         { *m = BuilderConfig_UnitTests{} }
func (m *BuilderConfig_UnitTests) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_UnitTests) ProtoMessage()    {}
func (*BuilderConfig_UnitTests) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 6}
}

func (m *BuilderConfig_UnitTests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_UnitTests.Unmarshal(m, b)
}
func (m *BuilderConfig_UnitTests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_UnitTests.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_UnitTests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_UnitTests.Merge(m, src)
}
func (m *BuilderConfig_UnitTests) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_UnitTests.Size(m)
}
func (m *BuilderConfig_UnitTests) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_UnitTests.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_UnitTests proto.InternalMessageInfo

func (m *BuilderConfig_UnitTests) GetPackageBlacklist() []*PackageInfo {
	if m != nil {
		return m.PackageBlacklist
	}
	return nil
}

func (m *BuilderConfig_UnitTests) GetEbuildsRunSpec() BuilderConfig_RunSpec {
	if m != nil {
		return m.EbuildsRunSpec
	}
	return BuilderConfig_RUN_SPEC_UNSPECIFIED
}

func (m *BuilderConfig_UnitTests) GetEmptySysroot() bool {
	if m != nil {
		return m.EmptySysroot
	}
	return false
}

// List of builder configs. Intended to be serialized to / from disk.
type BuilderConfigs struct {
	BuilderConfigs       []*BuilderConfig `protobuf:"bytes,1,rep,name=builder_configs,json=builderConfigs,proto3" json:"builder_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BuilderConfigs) Reset()         { *m = BuilderConfigs{} }
func (m *BuilderConfigs) String() string { return proto.CompactTextString(m) }
func (*BuilderConfigs) ProtoMessage()    {}
func (*BuilderConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{1}
}

func (m *BuilderConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfigs.Unmarshal(m, b)
}
func (m *BuilderConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfigs.Marshal(b, m, deterministic)
}
func (m *BuilderConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfigs.Merge(m, src)
}
func (m *BuilderConfigs) XXX_Size() int {
	return xxx_messageInfo_BuilderConfigs.Size(m)
}
func (m *BuilderConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfigs proto.InternalMessageInfo

func (m *BuilderConfigs) GetBuilderConfigs() []*BuilderConfig {
	if m != nil {
		return m.BuilderConfigs
	}
	return nil
}

func init() {
	proto.RegisterEnum("chromiumos.BuilderConfig_RunSpec", BuilderConfig_RunSpec_name, BuilderConfig_RunSpec_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_Id_Type", BuilderConfig_Id_Type_name, BuilderConfig_Id_Type_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_General_Environment", BuilderConfig_General_Environment_name, BuilderConfig_General_Environment_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_General_RunWhen_Mode", BuilderConfig_General_RunWhen_Mode_name, BuilderConfig_General_RunWhen_Mode_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_Artifacts_Prebuilts", BuilderConfig_Artifacts_Prebuilts_name, BuilderConfig_Artifacts_Prebuilts_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_Artifacts_ArtifactTypes", BuilderConfig_Artifacts_ArtifactTypes_name, BuilderConfig_Artifacts_ArtifactTypes_value)
	proto.RegisterType((*BuilderConfig)(nil), "chromiumos.BuilderConfig")
	proto.RegisterType((*BuilderConfig_Id)(nil), "chromiumos.BuilderConfig.Id")
	proto.RegisterType((*BuilderConfig_General)(nil), "chromiumos.BuilderConfig.General")
	proto.RegisterType((*BuilderConfig_General_RunWhen)(nil), "chromiumos.BuilderConfig.General.RunWhen")
	proto.RegisterType((*BuilderConfig_Orchestrator)(nil), "chromiumos.BuilderConfig.Orchestrator")
	proto.RegisterType((*BuilderConfig_Orchestrator_FollowOnOrchestrator)(nil), "chromiumos.BuilderConfig.Orchestrator.FollowOnOrchestrator")
	proto.RegisterType((*BuilderConfig_Artifacts)(nil), "chromiumos.BuilderConfig.Artifacts")
	proto.RegisterType((*BuilderConfig_Artifacts_PublishInfo)(nil), "chromiumos.BuilderConfig.Artifacts.PublishInfo")
	proto.RegisterType((*BuilderConfig_Chrome)(nil), "chromiumos.BuilderConfig.Chrome")
	proto.RegisterType((*BuilderConfig_Build)(nil), "chromiumos.BuilderConfig.Build")
	proto.RegisterType((*BuilderConfig_Build_PortageProfile)(nil), "chromiumos.BuilderConfig.Build.PortageProfile")
	proto.RegisterType((*BuilderConfig_Build_ToolchainStep)(nil), "chromiumos.BuilderConfig.Build.ToolchainStep")
	proto.RegisterType((*BuilderConfig_UnitTests)(nil), "chromiumos.BuilderConfig.UnitTests")
	proto.RegisterType((*BuilderConfigs)(nil), "chromiumos.BuilderConfigs")
}

func init() { proto.RegisterFile("chromiumos/builder_config.proto", fileDescriptor_6fe67302c16003fb) }

var fileDescriptor_6fe67302c16003fb = []byte{
	// 1710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x2e, 0x7f, 0xc4, 0x9f, 0x43, 0x91, 0x84, 0x56, 0xb2, 0x45, 0x23, 0x6e, 0xec, 0x2a, 0x6d,
	0xc7, 0x4d, 0x6a, 0x2a, 0x55, 0x12, 0x4f, 0x67, 0x72, 0xd1, 0x82, 0x24, 0x48, 0x23, 0x26, 0x01,
	0x74, 0x09, 0x4a, 0x71, 0xa6, 0x33, 0x3b, 0x20, 0xb8, 0x24, 0x31, 0x06, 0x01, 0x14, 0x00, 0xe3,
	0xd1, 0x63, 0xf4, 0xa2, 0xd3, 0x97, 0xe8, 0x7d, 0x2f, 0x7a, 0x99, 0x77, 0xe8, 0x45, 0x1f, 0xa2,
	0xcf, 0xd0, 0xd9, 0xc5, 0x8f, 0x40, 0x59, 0xb4, 0x34, 0xd3, 0xbb, 0x3d, 0x7b, 0xbe, 0xef, 0xec,
	0xd9, 0x3d, 0x07, 0xdf, 0x2e, 0xe0, 0x99, 0xb5, 0x0e, 0xbc, 0x8d, 0xbd, 0xdd, 0x78, 0xe1, 0xf9,
	0x7c, 0x6b, 0x3b, 0x0b, 0x1a, 0x10, 0xcb, 0x73, 0x97, 0xf6, 0xaa, 0xeb, 0x07, 0x5e, 0xe4, 0x21,
	0xb8, 0x01, 0x88, 0xa7, 0x39, 0xb0, 0xe5, 0x6d, 0x36, 0x9e, 0x1b, 0x83, 0xc4, 0x67, 0x2b, 0xcf,
	0x5b, 0x39, 0xf4, 0x9c, 0x5b, 0xf3, 0xed, 0xf2, 0x3c, 0xb2, 0x37, 0x34, 0x8c, 0xcc, 0x8d, 0x9f,
	0x00, 0x3e, 0xbd, 0x0d, 0x78, 0x1f, 0x98, 0xbe, 0x4f, 0x83, 0x30, 0xf6, 0x9f, 0xfd, 0xf7, 0x29,
	0x34, 0x7b, 0xf1, 0xf2, 0x7d, 0xbe, 0x3a, 0xfa, 0x2d, 0x14, 0xed, 0x45, 0xa7, 0xf0, 0xbc, 0xf0,
	0xa2, 0x71, 0xf1, 0xb4, 0x7b, 0xb3, 0x70, 0x77, 0x07, 0xd6, 0x55, 0x16, 0xb8, 0x68, 0x2f, 0xd0,
	0xb7, 0x50, 0x5d, 0x51, 0x97, 0x06, 0xa6, 0xd3, 0x29, 0x72, 0xca, 0x2f, 0xf6, 0x53, 0x46, 0x31,
	0x10, 0xa7, 0x0c, 0xf4, 0x1d, 0x1c, 0x7a, 0x81, 0xb5, 0xa6, 0x61, 0x14, 0x98, 0x91, 0x17, 0x74,
	0x4a, 0x3c, 0xc2, 0xaf, 0xf7, 0x47, 0xd0, 0x72, 0x68, 0xbc, 0xc3, 0x45, 0x12, 0xd4, 0xcd, 0x20,
	0xb2, 0x97, 0xa6, 0x15, 0x85, 0x9d, 0x32, 0x0f, 0xf4, 0xd9, 0xfe, 0x40, 0x52, 0x0a, 0xc5, 0x37,
	0x2c, 0xf4, 0x7b, 0xa8, 0x70, 0x02, 0xed, 0x1c, 0x70, 0xfe, 0xf3, 0xfd, 0xfc, 0x3e, 0xc7, 0xe1,
	0x04, 0x8f, 0xbe, 0x81, 0x03, 0x5e, 0xc3, 0x4e, 0x85, 0x13, 0x9f, 0xed, 0x27, 0x72, 0x0b, 0xc7,
	0x68, 0xd4, 0x03, 0xd8, 0xba, 0x76, 0x44, 0x22, 0x1a, 0x46, 0x61, 0xa7, 0x7a, 0x5f, 0xd2, 0x33,
	0xd7, 0x8e, 0x0c, 0x06, 0xc5, 0xf5, 0x6d, 0x3a, 0x14, 0xff, 0x51, 0x80, 0xa2, 0xb2, 0x40, 0x08,
	0xca, 0xae, 0xb9, 0xa1, 0xbc, 0x6e, 0x75, 0xcc, 0xc7, 0xe8, 0x31, 0x54, 0xe6, 0x81, 0xe9, 0x5a,
	0x6b, 0x5e, 0x9a, 0x3a, 0x4e, 0x2c, 0xf4, 0x0d, 0x94, 0xa3, 0x6b, 0x9f, 0xf2, 0xe3, 0x6e, 0x7d,
	0xac, 0x60, 0xca, 0xa2, 0x6b, 0x5c, 0xfb, 0x14, 0x73, 0xf8, 0x59, 0x1f, 0xca, 0xcc, 0x42, 0x27,
	0x20, 0x18, 0x6f, 0x75, 0x99, 0xcc, 0xd4, 0xa9, 0x2e, 0xf7, 0x95, 0xa1, 0x22, 0x0f, 0x84, 0x9f,
	0xa1, 0x0a, 0x14, 0xfb, 0x7f, 0x12, 0x0a, 0xa8, 0x05, 0xa0, 0x6b, 0x53, 0x63, 0x3a, 0xeb, 0x4d,
	0x14, 0x43, 0x28, 0xa2, 0x26, 0xd4, 0x0d, 0x4d, 0x1b, 0xf7, 0x5f, 0x4b, 0x8a, 0x2a, 0x94, 0xc4,
	0x7f, 0x95, 0xa1, 0x9a, 0xf4, 0x01, 0x7a, 0x05, 0x35, 0x2b, 0xb0, 0x23, 0xdb, 0x32, 0x9d, 0xa4,
	0xdf, 0xc4, 0x6e, 0xdc, 0xae, 0xdd, 0xb4, 0x5d, 0xbb, 0x3d, 0xcf, 0x73, 0x2e, 0x4d, 0x67, 0x4b,
	0x71, 0x86, 0x45, 0x1a, 0x34, 0xa8, 0xfb, 0xa3, 0x1d, 0x78, 0xee, 0x86, 0xba, 0x11, 0xdf, 0x5c,
	0xeb, 0xe2, 0xe5, 0xbd, 0x7d, 0xd7, 0x95, 0x6f, 0x48, 0x38, 0x1f, 0x01, 0x0d, 0xa0, 0x16, 0x6c,
	0x5d, 0xf2, 0x7e, 0x4d, 0xdd, 0xa4, 0x07, 0x7f, 0x73, 0x7f, 0x34, 0xbc, 0x75, 0xaf, 0xd6, 0xd4,
	0xc5, 0xd5, 0x20, 0x1e, 0xa0, 0x3f, 0x40, 0x73, 0x1e, 0x78, 0xef, 0xa8, 0x4b, 0xe6, 0x74, 0xe9,
	0x05, 0x34, 0xe9, 0xc2, 0x0f, 0xf7, 0x64, 0xa4, 0xdf, 0x28, 0x3e, 0x8c, 0x09, 0x3d, 0x8e, 0x17,
	0xff, 0x5d, 0x80, 0x6a, 0x12, 0x15, 0xf5, 0xa0, 0xbc, 0xf1, 0x16, 0x71, 0x3d, 0x5b, 0x17, 0xdd,
	0x07, 0xa7, 0xd3, 0x9d, 0x78, 0x0b, 0x8a, 0x39, 0x17, 0x7d, 0x06, 0xcd, 0xa5, 0xed, 0x50, 0xe2,
	0x9b, 0x51, 0x44, 0x03, 0x37, 0xec, 0x14, 0x9f, 0x97, 0x5e, 0xd4, 0xf1, 0x21, 0x9b, 0xd4, 0x93,
	0xb9, 0xb3, 0x39, 0x94, 0x19, 0x85, 0x55, 0x75, 0xa2, 0x0d, 0x6e, 0x57, 0xb5, 0x05, 0x20, 0x8d,
	0xaf, 0xa4, 0xb7, 0x53, 0x82, 0x67, 0xaa, 0x50, 0x40, 0x22, 0x3c, 0xd6, 0xd4, 0xf1, 0x5b, 0x66,
	0x11, 0x4d, 0x25, 0x43, 0x65, 0x2c, 0x93, 0x89, 0x64, 0xf4, 0x5f, 0x0b, 0x45, 0xd4, 0x81, 0x13,
	0x55, 0xbb, 0xc3, 0x53, 0x3a, 0x1b, 0x41, 0x23, 0x77, 0xf6, 0xe8, 0x13, 0x38, 0x95, 0xd5, 0x4b,
	0x05, 0x6b, 0xea, 0x44, 0x56, 0x8d, 0x0f, 0x57, 0xd4, 0xb1, 0x36, 0x98, 0xf5, 0x0d, 0x45, 0x63,
	0x2b, 0x36, 0xa0, 0x3a, 0x35, 0xa4, 0x91, 0xa2, 0x8e, 0x84, 0xa2, 0xf8, 0x9f, 0x22, 0x1c, 0xe6,
	0x35, 0x00, 0x89, 0x50, 0xb3, 0xd6, 0xb6, 0xb3, 0x08, 0xa8, 0xdb, 0x29, 0xf0, 0xdd, 0x65, 0x36,
	0xfa, 0x23, 0xb4, 0x56, 0x76, 0x64, 0x3b, 0x34, 0x24, 0x4c, 0x33, 0xed, 0x28, 0x51, 0xa8, 0x27,
	0xf9, 0xc3, 0x1c, 0xc5, 0x88, 0x3e, 0x07, 0xe0, 0xe6, 0x2a, 0x6f, 0xa2, 0xbf, 0xc0, 0xe3, 0xa5,
	0xe7, 0x38, 0xde, 0x7b, 0xe2, 0xb9, 0xe4, 0x0e, 0xa5, 0xfa, 0xf6, 0x61, 0x4a, 0xd5, 0x1d, 0xf2,
	0x20, 0x9a, 0xbb, 0x23, 0x5f, 0x27, 0xcb, 0x3b, 0x66, 0xc5, 0x6b, 0x38, 0xb9, 0x0b, 0x8d, 0xbe,
	0xde, 0x9b, 0x4a, 0xfc, 0xc5, 0xdf, 0x19, 0x0d, 0x7d, 0x01, 0xe8, 0xbd, 0x69, 0x47, 0x64, 0xe9,
	0x05, 0x24, 0xa3, 0xf3, 0x63, 0xa8, 0xe1, 0x36, 0xf3, 0x0c, 0xbd, 0x20, 0x5d, 0x4e, 0xfc, 0x5b,
	0x0d, 0xea, 0x99, 0x2e, 0xa2, 0x37, 0x50, 0xf7, 0x03, 0xca, 0x74, 0x2a, 0x0a, 0x93, 0x2e, 0x7c,
	0xf9, 0x00, 0x3d, 0xed, 0xea, 0x29, 0x09, 0xdf, 0xf0, 0xd1, 0xf7, 0xd0, 0x4a, 0x65, 0x96, 0x30,
	0x2d, 0x89, 0x5b, 0xb1, 0x75, 0xf1, 0xbb, 0x87, 0x44, 0x4c, 0x47, 0x4c, 0x7c, 0x42, 0xdc, 0x34,
	0xf3, 0x26, 0xea, 0xc2, 0x71, 0xb6, 0x0c, 0x59, 0x85, 0x64, 0xbe, 0xb5, 0xde, 0xd1, 0x88, 0xd7,
	0xa7, 0x8e, 0x8f, 0x32, 0xd7, 0x28, 0xec, 0x71, 0x07, 0xc3, 0x67, 0x82, 0x9f, 0xc3, 0x97, 0x63,
	0x7c, 0xe6, 0xca, 0xf0, 0x7f, 0x86, 0x23, 0x7f, 0x3b, 0x77, 0xec, 0x70, 0x4d, 0x6e, 0xae, 0x97,
	0x83, 0xe7, 0xa5, 0x17, 0x8d, 0x8b, 0xf3, 0x07, 0x1d, 0x47, 0x4c, 0x56, 0xdc, 0xa5, 0x87, 0x85,
	0x24, 0x52, 0xe6, 0x15, 0xff, 0x5a, 0x80, 0x46, 0x0e, 0x81, 0x3e, 0xbf, 0x59, 0xed, 0x26, 0xb7,
	0xb8, 0xc0, 0xed, 0xc4, 0x91, 0x65, 0x76, 0x09, 0xcd, 0x14, 0xfb, 0x7f, 0x1e, 0xe9, 0x61, 0x12,
	0x87, 0x5b, 0x67, 0x0a, 0xd4, 0xb3, 0x1a, 0xa2, 0x27, 0xf0, 0x48, 0xc7, 0x72, 0x6f, 0xa6, 0x8c,
	0x8d, 0xe9, 0xad, 0x0f, 0x15, 0xa0, 0xa2, 0xcf, 0x7a, 0x63, 0xa5, 0x1f, 0x7f, 0xa4, 0x3a, 0x56,
	0x2e, 0x25, 0x43, 0x16, 0x8a, 0xa8, 0x06, 0x65, 0x55, 0x53, 0x65, 0xa1, 0x74, 0xf6, 0x53, 0x09,
	0x9a, 0x3b, 0x4b, 0xa1, 0x4f, 0x41, 0x94, 0xb0, 0xa1, 0x0c, 0xa5, 0xbe, 0x41, 0xd8, 0x25, 0x72,
	0x3b, 0x68, 0x13, 0xea, 0xca, 0x44, 0x1a, 0xc9, 0xe4, 0x07, 0x45, 0x17, 0x0a, 0xe8, 0x14, 0x8e,
	0x0d, 0x79, 0x6a, 0x90, 0x99, 0x3e, 0x90, 0x0c, 0x99, 0xe8, 0xd2, 0xdb, 0xb1, 0x26, 0x0d, 0x84,
	0x22, 0x42, 0xd0, 0x92, 0x66, 0x86, 0xc6, 0x9d, 0x4c, 0x6a, 0xa6, 0x42, 0x89, 0x29, 0x87, 0x21,
	0x65, 0x76, 0x99, 0x91, 0x75, 0x45, 0x55, 0xe5, 0x01, 0x19, 0xcd, 0x18, 0x8e, 0x07, 0x9e, 0x0a,
	0x07, 0xe8, 0x10, 0x6a, 0x43, 0x05, 0x4f, 0xae, 0x24, 0x2c, 0x0b, 0x15, 0xd4, 0x86, 0x06, 0xdf,
	0xe0, 0x80, 0x8c, 0xb5, 0xd1, 0x54, 0xa8, 0xa2, 0x63, 0x68, 0xf7, 0x5f, 0x63, 0x6d, 0x22, 0x6b,
	0x53, 0xd2, 0xd7, 0xd4, 0xa1, 0x32, 0x12, 0x6a, 0x2c, 0x78, 0x5f, 0x97, 0x09, 0x96, 0x75, 0x0d,
	0x1b, 0x42, 0x9d, 0x25, 0x10, 0x27, 0x2a, 0xe1, 0xfe, 0x6b, 0xe5, 0x52, 0x9e, 0x0a, 0x80, 0x9e,
	0x42, 0x67, 0xa6, 0x5e, 0xca, 0x98, 0x6f, 0x86, 0x68, 0x78, 0x20, 0x63, 0x45, 0x1d, 0xf1, 0x7c,
	0x84, 0x06, 0x93, 0xce, 0x3d, 0xbe, 0x43, 0x76, 0x2c, 0xf1, 0x92, 0xa4, 0x3f, 0x96, 0xd4, 0x11,
	0xb9, 0x92, 0xb0, 0xaa, 0xa8, 0xa3, 0x69, 0xec, 0x6f, 0xde, 0x8a, 0x3c, 0x1e, 0x5f, 0x4e, 0x88,
	0x3e, 0xd2, 0x62, 0x6f, 0x0b, 0x3d, 0x83, 0x4f, 0x72, 0xde, 0x24, 0x90, 0x34, 0x1c, 0x24, 0x80,
	0x36, 0xfa, 0x39, 0x3c, 0xd9, 0xef, 0x16, 0x76, 0xdc, 0x6f, 0x64, 0xac, 0xca, 0xe3, 0x9c, 0xfb,
	0x48, 0xfc, 0x25, 0x54, 0xe2, 0xe7, 0x0e, 0x53, 0x5b, 0xdb, 0x65, 0xd7, 0x46, 0x72, 0x61, 0xd7,
	0x70, 0x66, 0x8b, 0x7f, 0xaf, 0xc0, 0x01, 0x6f, 0x37, 0xf4, 0x25, 0xd4, 0xb7, 0x21, 0x25, 0x4b,
	0xc7, 0x5c, 0x85, 0x5c, 0x94, 0x1b, 0x17, 0xc7, 0xf9, 0xa6, 0x9c, 0x85, 0x74, 0xe8, 0x98, 0x2b,
	0x5c, 0xdb, 0xc6, 0x83, 0x10, 0x5d, 0x41, 0xdb, 0xf7, 0x82, 0xc8, 0x5c, 0x51, 0xe2, 0x07, 0x1e,
	0xbb, 0x9e, 0x12, 0xa9, 0xee, 0xde, 0xf3, 0x90, 0xea, 0xea, 0x31, 0x4d, 0x8f, 0x59, 0xb8, 0xe5,
	0xef, 0xd8, 0xe8, 0x15, 0x34, 0xec, 0x0d, 0x0b, 0x1b, 0x7f, 0x21, 0x25, 0xfe, 0x85, 0x3c, 0xca,
	0x07, 0x55, 0x98, 0x9b, 0x3f, 0x72, 0xc0, 0x4e, 0x87, 0x21, 0x1a, 0x83, 0x60, 0xbb, 0x61, 0x64,
	0x3a, 0x0e, 0xf1, 0x4d, 0xeb, 0x9d, 0xb9, 0xa2, 0xf1, 0x9b, 0xf2, 0xa3, 0xaf, 0x25, 0xbc, 0x75,
	0xa7, 0x3e, 0xb5, 0x70, 0x3b, 0xa1, 0xea, 0x09, 0x13, 0x7d, 0x01, 0x47, 0x96, 0xb7, 0xf1, 0xd9,
	0x55, 0x1c, 0x79, 0x9e, 0x63, 0xad, 0x4d, 0xdb, 0xe5, 0x4f, 0xcc, 0x1a, 0x16, 0x12, 0x87, 0x91,
	0xce, 0xa3, 0x2f, 0xe1, 0xc4, 0xf4, 0x7d, 0xe7, 0x9a, 0xac, 0x68, 0x10, 0xd8, 0x11, 0xb1, 0xd6,
	0xa6, 0xcb, 0x96, 0xaf, 0x70, 0x3c, 0xe2, 0xbe, 0x11, 0x77, 0xf5, 0x63, 0x0f, 0xfa, 0x0a, 0x6a,
	0x59, 0x92, 0x55, 0x7e, 0xdc, 0xa7, 0xf9, 0x24, 0x93, 0x34, 0xb8, 0x02, 0x65, 0x40, 0x74, 0x09,
	0xed, 0x2c, 0x17, 0x12, 0x46, 0xd4, 0x0f, 0x3b, 0x35, 0xce, 0x7d, 0x79, 0xdf, 0x91, 0x67, 0xa9,
	0x4e, 0x23, 0xea, 0xe3, 0x56, 0x94, 0x37, 0x43, 0xf4, 0x2b, 0x68, 0xa5, 0x7b, 0x0d, 0xbd, 0x6d,
	0x60, 0xd1, 0x0e, 0xf0, 0xc4, 0x9b, 0xc9, 0xec, 0x94, 0x4f, 0x8a, 0x9f, 0x43, 0x6b, 0xb7, 0x74,
	0xa8, 0x03, 0xd5, 0xb4, 0xf6, 0xb1, 0xe0, 0xa5, 0xa6, 0xf8, 0xcf, 0x02, 0x34, 0x77, 0x16, 0x45,
	0x06, 0x9c, 0xc6, 0xbf, 0x10, 0x11, 0x25, 0xb7, 0xee, 0x95, 0x02, 0x2f, 0xf1, 0xce, 0x7f, 0x0b,
	0xeb, 0xe5, 0xbc, 0x0a, 0xe1, 0x47, 0x29, 0x79, 0x57, 0x9b, 0x74, 0x78, 0xf4, 0x23, 0x0d, 0xec,
	0xe5, 0x35, 0xb9, 0xf3, 0xae, 0xfa, 0x78, 0xcc, 0xe3, 0x98, 0xba, 0x13, 0xf1, 0xbb, 0x72, 0xad,
	0x2e, 0x80, 0xf8, 0x53, 0x01, 0xea, 0xd9, 0xd3, 0x1d, 0x0d, 0xe0, 0x28, 0x29, 0x02, 0x99, 0x3b,
	0xa6, 0xf5, 0xce, 0xb1, 0x43, 0x76, 0xfd, 0x7c, 0xb4, 0x6c, 0x42, 0xc2, 0xe8, 0xa5, 0x04, 0xf4,
	0x06, 0x04, 0x2e, 0xd1, 0x8b, 0x90, 0xb0, 0x97, 0x6b, 0xe8, 0x53, 0x8b, 0x77, 0xd4, 0x83, 0x1a,
	0xb4, 0x95, 0x50, 0x13, 0x9b, 0xbd, 0x13, 0xe9, 0xc6, 0x8f, 0xae, 0x49, 0x78, 0x1d, 0x06, 0x9e,
	0x17, 0x25, 0xbd, 0x76, 0xc8, 0x27, 0xa7, 0xf1, 0xdc, 0xd9, 0x90, 0xbf, 0x4d, 0x39, 0xbe, 0x03,
	0x27, 0xec, 0x95, 0xc7, 0x74, 0xfb, 0xc3, 0x3b, 0x21, 0x7e, 0x02, 0x0a, 0x05, 0x54, 0x85, 0x12,
	0x1b, 0x14, 0x99, 0xdc, 0x32, 0xb8, 0xfc, 0xbd, 0x62, 0x08, 0xa5, 0x33, 0x03, 0x5a, 0x3b, 0x59,
	0x85, 0xa8, 0x07, 0xed, 0xdd, 0x1f, 0xe0, 0x54, 0x35, 0x9e, 0xec, 0xdd, 0x0a, 0x6e, 0xcd, 0x77,
	0x62, 0xf4, 0x5e, 0xfd, 0xf0, 0xf5, 0xca, 0xcb, 0xe0, 0x5d, 0x2f, 0x58, 0x9d, 0xe7, 0x7e, 0x99,
	0x6d, 0x77, 0x19, 0x98, 0xf1, 0x2f, 0xf0, 0xf9, 0xca, 0xcb, 0x79, 0xe6, 0x15, 0x3e, 0xf9, 0xd5,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x50, 0x80, 0x53, 0x9a, 0x8e, 0x0f, 0x00, 0x00,
}
