// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analysis_service/analysis_service.proto

package analysis_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	api "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Requests and responses are sent to the Artifacts Analysis Service on a single
// Pub/Sub topic; thus, the type of the request and response need to be encoded
// in the Pub/Sub message. This is done with this wrapper proto.
//
// This proto should only be used by a recipes module to do the wrapping and a
// layer on the Analysis Server to do the unwrapping.
//
// NEXT ID: 44;
type AnalysisServiceEvent struct {
	// The Buildbucket id for the build doing the request and response.
	BuildId int64 `protobuf:"varint,42,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// The name of the step doing the request and response. Must be the same
	// format as Buildbucket Build proto's step name (i.e. parent and child step
	// names are separated by the "|" character).
	StepName string `protobuf:"bytes,43,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	// The time the request and response were sent and recieved by the caller.
	RequestTime  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	ResponseTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	// The request to upload.
	//
	// Types that are valid to be assigned to Request:
	//	*AnalysisServiceEvent_InstallPackagesRequest
	//	*AnalysisServiceEvent_BundleRequest
	//	*AnalysisServiceEvent_BundleVmFilesRequest
	//	*AnalysisServiceEvent_BinhostGetRequest
	//	*AnalysisServiceEvent_AclArgsRequest
	//	*AnalysisServiceEvent_PrepareBinhostUploadsRequest
	//	*AnalysisServiceEvent_SetBinhostRequest
	//	*AnalysisServiceEvent_RegenBuildCacheRequest
	//	*AnalysisServiceEvent_GetBuildDependencyGraphRequest
	//	*AnalysisServiceEvent_CreateImageRequest
	//	*AnalysisServiceEvent_TestImageRequest
	//	*AnalysisServiceEvent_CreateRequest
	//	*AnalysisServiceEvent_UpdateRequest
	//	*AnalysisServiceEvent_SysrootCreateRequest
	//	*AnalysisServiceEvent_InstallToolchainRequest
	//	*AnalysisServiceEvent_BuildTargetUnitTestRequest
	//	*AnalysisServiceEvent_ChromiteUnitTestRequest
	//	*AnalysisServiceEvent_DebugInfoTestRequest
	//	*AnalysisServiceEvent_VmTestRequest
	//	*AnalysisServiceEvent_MoblabVmTestRequest
	Request isAnalysisServiceEvent_Request `protobuf_oneof:"request"`
	// The response to upload.
	//
	// Types that are valid to be assigned to Response:
	//	*AnalysisServiceEvent_InstallPackagesResponse
	//	*AnalysisServiceEvent_BundleResponse
	//	*AnalysisServiceEvent_BinhostGetResponse
	//	*AnalysisServiceEvent_AclArgsResponse
	//	*AnalysisServiceEvent_PrepareBinhostUploadsResponse
	//	*AnalysisServiceEvent_SetBinhostResponse
	//	*AnalysisServiceEvent_RegenBuildCacheResponse
	//	*AnalysisServiceEvent_GetBuildDependencyGraphResponse
	//	*AnalysisServiceEvent_CreateImageResult
	//	*AnalysisServiceEvent_TestImageResult
	//	*AnalysisServiceEvent_CreateResponse
	//	*AnalysisServiceEvent_UpdateResponse
	//	*AnalysisServiceEvent_SysrootCreateResponse
	//	*AnalysisServiceEvent_InstallToolchainResponse
	//	*AnalysisServiceEvent_BuildTargetUnitTestResponse
	//	*AnalysisServiceEvent_ChromiteUnitTestResponse
	//	*AnalysisServiceEvent_DebugInfoTestResponse
	//	*AnalysisServiceEvent_VmTestResponse
	//	*AnalysisServiceEvent_MoblabVmTestResponse
	Response             isAnalysisServiceEvent_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AnalysisServiceEvent) Reset()         { *m = AnalysisServiceEvent{} }
func (m *AnalysisServiceEvent) String() string { return proto.CompactTextString(m) }
func (*AnalysisServiceEvent) ProtoMessage()    {}
func (*AnalysisServiceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c22ab0fbdfe575, []int{0}
}

func (m *AnalysisServiceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalysisServiceEvent.Unmarshal(m, b)
}
func (m *AnalysisServiceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalysisServiceEvent.Marshal(b, m, deterministic)
}
func (m *AnalysisServiceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalysisServiceEvent.Merge(m, src)
}
func (m *AnalysisServiceEvent) XXX_Size() int {
	return xxx_messageInfo_AnalysisServiceEvent.Size(m)
}
func (m *AnalysisServiceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalysisServiceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AnalysisServiceEvent proto.InternalMessageInfo

func (m *AnalysisServiceEvent) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *AnalysisServiceEvent) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

func (m *AnalysisServiceEvent) GetRequestTime() *timestamp.Timestamp {
	if m != nil {
		return m.RequestTime
	}
	return nil
}

func (m *AnalysisServiceEvent) GetResponseTime() *timestamp.Timestamp {
	if m != nil {
		return m.ResponseTime
	}
	return nil
}

type isAnalysisServiceEvent_Request interface {
	isAnalysisServiceEvent_Request()
}

type AnalysisServiceEvent_InstallPackagesRequest struct {
	InstallPackagesRequest *api.InstallPackagesRequest `protobuf:"bytes,1,opt,name=install_packages_request,json=installPackagesRequest,proto3,oneof"`
}

type AnalysisServiceEvent_BundleRequest struct {
	BundleRequest *api.BundleRequest `protobuf:"bytes,5,opt,name=bundle_request,json=bundleRequest,proto3,oneof"`
}

type AnalysisServiceEvent_BundleVmFilesRequest struct {
	BundleVmFilesRequest *api.BundleVmFilesRequest `protobuf:"bytes,7,opt,name=bundle_vm_files_request,json=bundleVmFilesRequest,proto3,oneof"`
}

type AnalysisServiceEvent_BinhostGetRequest struct {
	BinhostGetRequest *api.BinhostGetRequest `protobuf:"bytes,8,opt,name=binhost_get_request,json=binhostGetRequest,proto3,oneof"`
}

type AnalysisServiceEvent_AclArgsRequest struct {
	AclArgsRequest *api.AclArgsRequest `protobuf:"bytes,10,opt,name=acl_args_request,json=aclArgsRequest,proto3,oneof"`
}

type AnalysisServiceEvent_PrepareBinhostUploadsRequest struct {
	PrepareBinhostUploadsRequest *api.PrepareBinhostUploadsRequest `protobuf:"bytes,12,opt,name=prepare_binhost_uploads_request,json=prepareBinhostUploadsRequest,proto3,oneof"`
}

type AnalysisServiceEvent_SetBinhostRequest struct {
	SetBinhostRequest *api.SetBinhostRequest `protobuf:"bytes,14,opt,name=set_binhost_request,json=setBinhostRequest,proto3,oneof"`
}

type AnalysisServiceEvent_RegenBuildCacheRequest struct {
	RegenBuildCacheRequest *api.RegenBuildCacheRequest `protobuf:"bytes,16,opt,name=regen_build_cache_request,json=regenBuildCacheRequest,proto3,oneof"`
}

type AnalysisServiceEvent_GetBuildDependencyGraphRequest struct {
	GetBuildDependencyGraphRequest *api.GetBuildDependencyGraphRequest `protobuf:"bytes,18,opt,name=get_build_dependency_graph_request,json=getBuildDependencyGraphRequest,proto3,oneof"`
}

type AnalysisServiceEvent_CreateImageRequest struct {
	CreateImageRequest *api.CreateImageRequest `protobuf:"bytes,20,opt,name=create_image_request,json=createImageRequest,proto3,oneof"`
}

type AnalysisServiceEvent_TestImageRequest struct {
	TestImageRequest *api.TestImageRequest `protobuf:"bytes,22,opt,name=test_image_request,json=testImageRequest,proto3,oneof"`
}

type AnalysisServiceEvent_CreateRequest struct {
	CreateRequest *api.CreateRequest `protobuf:"bytes,24,opt,name=create_request,json=createRequest,proto3,oneof"`
}

type AnalysisServiceEvent_UpdateRequest struct {
	UpdateRequest *api.UpdateRequest `protobuf:"bytes,26,opt,name=update_request,json=updateRequest,proto3,oneof"`
}

type AnalysisServiceEvent_SysrootCreateRequest struct {
	SysrootCreateRequest *api.SysrootCreateRequest `protobuf:"bytes,28,opt,name=sysroot_create_request,json=sysrootCreateRequest,proto3,oneof"`
}

type AnalysisServiceEvent_InstallToolchainRequest struct {
	InstallToolchainRequest *api.InstallToolchainRequest `protobuf:"bytes,30,opt,name=install_toolchain_request,json=installToolchainRequest,proto3,oneof"`
}

type AnalysisServiceEvent_BuildTargetUnitTestRequest struct {
	BuildTargetUnitTestRequest *api.BuildTargetUnitTestRequest `protobuf:"bytes,32,opt,name=build_target_unit_test_request,json=buildTargetUnitTestRequest,proto3,oneof"`
}

type AnalysisServiceEvent_ChromiteUnitTestRequest struct {
	ChromiteUnitTestRequest *api.ChromiteUnitTestRequest `protobuf:"bytes,34,opt,name=chromite_unit_test_request,json=chromiteUnitTestRequest,proto3,oneof"`
}

type AnalysisServiceEvent_DebugInfoTestRequest struct {
	DebugInfoTestRequest *api.DebugInfoTestRequest `protobuf:"bytes,36,opt,name=debug_info_test_request,json=debugInfoTestRequest,proto3,oneof"`
}

type AnalysisServiceEvent_VmTestRequest struct {
	VmTestRequest *api.VmTestRequest `protobuf:"bytes,38,opt,name=vm_test_request,json=vmTestRequest,proto3,oneof"`
}

type AnalysisServiceEvent_MoblabVmTestRequest struct {
	MoblabVmTestRequest *api.MoblabVmTestRequest `protobuf:"bytes,40,opt,name=moblab_vm_test_request,json=moblabVmTestRequest,proto3,oneof"`
}

func (*AnalysisServiceEvent_InstallPackagesRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_BundleRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_BundleVmFilesRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_BinhostGetRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_AclArgsRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_PrepareBinhostUploadsRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_SetBinhostRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_RegenBuildCacheRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_GetBuildDependencyGraphRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_CreateImageRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_TestImageRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_CreateRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_UpdateRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_SysrootCreateRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_InstallToolchainRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_BuildTargetUnitTestRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_ChromiteUnitTestRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_DebugInfoTestRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_VmTestRequest) isAnalysisServiceEvent_Request() {}

func (*AnalysisServiceEvent_MoblabVmTestRequest) isAnalysisServiceEvent_Request() {}

func (m *AnalysisServiceEvent) GetRequest() isAnalysisServiceEvent_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *AnalysisServiceEvent) GetInstallPackagesRequest() *api.InstallPackagesRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_InstallPackagesRequest); ok {
		return x.InstallPackagesRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBundleRequest() *api.BundleRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_BundleRequest); ok {
		return x.BundleRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBundleVmFilesRequest() *api.BundleVmFilesRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_BundleVmFilesRequest); ok {
		return x.BundleVmFilesRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBinhostGetRequest() *api.BinhostGetRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_BinhostGetRequest); ok {
		return x.BinhostGetRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetAclArgsRequest() *api.AclArgsRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_AclArgsRequest); ok {
		return x.AclArgsRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetPrepareBinhostUploadsRequest() *api.PrepareBinhostUploadsRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_PrepareBinhostUploadsRequest); ok {
		return x.PrepareBinhostUploadsRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetSetBinhostRequest() *api.SetBinhostRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_SetBinhostRequest); ok {
		return x.SetBinhostRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetRegenBuildCacheRequest() *api.RegenBuildCacheRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_RegenBuildCacheRequest); ok {
		return x.RegenBuildCacheRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetGetBuildDependencyGraphRequest() *api.GetBuildDependencyGraphRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_GetBuildDependencyGraphRequest); ok {
		return x.GetBuildDependencyGraphRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetCreateImageRequest() *api.CreateImageRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_CreateImageRequest); ok {
		return x.CreateImageRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetTestImageRequest() *api.TestImageRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_TestImageRequest); ok {
		return x.TestImageRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetCreateRequest() *api.CreateRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_CreateRequest); ok {
		return x.CreateRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetUpdateRequest() *api.UpdateRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_UpdateRequest); ok {
		return x.UpdateRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetSysrootCreateRequest() *api.SysrootCreateRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_SysrootCreateRequest); ok {
		return x.SysrootCreateRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetInstallToolchainRequest() *api.InstallToolchainRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_InstallToolchainRequest); ok {
		return x.InstallToolchainRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBuildTargetUnitTestRequest() *api.BuildTargetUnitTestRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_BuildTargetUnitTestRequest); ok {
		return x.BuildTargetUnitTestRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetChromiteUnitTestRequest() *api.ChromiteUnitTestRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_ChromiteUnitTestRequest); ok {
		return x.ChromiteUnitTestRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetDebugInfoTestRequest() *api.DebugInfoTestRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_DebugInfoTestRequest); ok {
		return x.DebugInfoTestRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetVmTestRequest() *api.VmTestRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_VmTestRequest); ok {
		return x.VmTestRequest
	}
	return nil
}

func (m *AnalysisServiceEvent) GetMoblabVmTestRequest() *api.MoblabVmTestRequest {
	if x, ok := m.GetRequest().(*AnalysisServiceEvent_MoblabVmTestRequest); ok {
		return x.MoblabVmTestRequest
	}
	return nil
}

type isAnalysisServiceEvent_Response interface {
	isAnalysisServiceEvent_Response()
}

type AnalysisServiceEvent_InstallPackagesResponse struct {
	InstallPackagesResponse *api.InstallPackagesResponse `protobuf:"bytes,2,opt,name=install_packages_response,json=installPackagesResponse,proto3,oneof"`
}

type AnalysisServiceEvent_BundleResponse struct {
	BundleResponse *api.BundleResponse `protobuf:"bytes,6,opt,name=bundle_response,json=bundleResponse,proto3,oneof"`
}

type AnalysisServiceEvent_BinhostGetResponse struct {
	BinhostGetResponse *api.BinhostGetResponse `protobuf:"bytes,9,opt,name=binhost_get_response,json=binhostGetResponse,proto3,oneof"`
}

type AnalysisServiceEvent_AclArgsResponse struct {
	AclArgsResponse *api.AclArgsResponse `protobuf:"bytes,11,opt,name=acl_args_response,json=aclArgsResponse,proto3,oneof"`
}

type AnalysisServiceEvent_PrepareBinhostUploadsResponse struct {
	PrepareBinhostUploadsResponse *api.PrepareBinhostUploadsResponse `protobuf:"bytes,13,opt,name=prepare_binhost_uploads_response,json=prepareBinhostUploadsResponse,proto3,oneof"`
}

type AnalysisServiceEvent_SetBinhostResponse struct {
	SetBinhostResponse *api.SetBinhostResponse `protobuf:"bytes,15,opt,name=set_binhost_response,json=setBinhostResponse,proto3,oneof"`
}

type AnalysisServiceEvent_RegenBuildCacheResponse struct {
	RegenBuildCacheResponse *api.RegenBuildCacheResponse `protobuf:"bytes,17,opt,name=regen_build_cache_response,json=regenBuildCacheResponse,proto3,oneof"`
}

type AnalysisServiceEvent_GetBuildDependencyGraphResponse struct {
	GetBuildDependencyGraphResponse *api.GetBuildDependencyGraphResponse `protobuf:"bytes,19,opt,name=get_build_dependency_graph_response,json=getBuildDependencyGraphResponse,proto3,oneof"`
}

type AnalysisServiceEvent_CreateImageResult struct {
	CreateImageResult *api.CreateImageResult `protobuf:"bytes,21,opt,name=create_image_result,json=createImageResult,proto3,oneof"`
}

type AnalysisServiceEvent_TestImageResult struct {
	TestImageResult *api.TestImageResult `protobuf:"bytes,23,opt,name=test_image_result,json=testImageResult,proto3,oneof"`
}

type AnalysisServiceEvent_CreateResponse struct {
	CreateResponse *api.CreateResponse `protobuf:"bytes,25,opt,name=create_response,json=createResponse,proto3,oneof"`
}

type AnalysisServiceEvent_UpdateResponse struct {
	UpdateResponse *api.UpdateResponse `protobuf:"bytes,27,opt,name=update_response,json=updateResponse,proto3,oneof"`
}

type AnalysisServiceEvent_SysrootCreateResponse struct {
	SysrootCreateResponse *api.SysrootCreateResponse `protobuf:"bytes,29,opt,name=sysroot_create_response,json=sysrootCreateResponse,proto3,oneof"`
}

type AnalysisServiceEvent_InstallToolchainResponse struct {
	InstallToolchainResponse *api.InstallToolchainResponse `protobuf:"bytes,31,opt,name=install_toolchain_response,json=installToolchainResponse,proto3,oneof"`
}

type AnalysisServiceEvent_BuildTargetUnitTestResponse struct {
	BuildTargetUnitTestResponse *api.BuildTargetUnitTestResponse `protobuf:"bytes,33,opt,name=build_target_unit_test_response,json=buildTargetUnitTestResponse,proto3,oneof"`
}

type AnalysisServiceEvent_ChromiteUnitTestResponse struct {
	ChromiteUnitTestResponse *api.ChromiteUnitTestResponse `protobuf:"bytes,35,opt,name=chromite_unit_test_response,json=chromiteUnitTestResponse,proto3,oneof"`
}

type AnalysisServiceEvent_DebugInfoTestResponse struct {
	DebugInfoTestResponse *api.DebugInfoTestResponse `protobuf:"bytes,37,opt,name=debug_info_test_response,json=debugInfoTestResponse,proto3,oneof"`
}

type AnalysisServiceEvent_VmTestResponse struct {
	VmTestResponse *api.VmTestResponse `protobuf:"bytes,39,opt,name=vm_test_response,json=vmTestResponse,proto3,oneof"`
}

type AnalysisServiceEvent_MoblabVmTestResponse struct {
	MoblabVmTestResponse *api.MoblabVmTestResponse `protobuf:"bytes,41,opt,name=moblab_vm_test_response,json=moblabVmTestResponse,proto3,oneof"`
}

func (*AnalysisServiceEvent_InstallPackagesResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_BundleResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_BinhostGetResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_AclArgsResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_PrepareBinhostUploadsResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_SetBinhostResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_RegenBuildCacheResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_GetBuildDependencyGraphResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_CreateImageResult) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_TestImageResult) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_CreateResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_UpdateResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_SysrootCreateResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_InstallToolchainResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_BuildTargetUnitTestResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_ChromiteUnitTestResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_DebugInfoTestResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_VmTestResponse) isAnalysisServiceEvent_Response() {}

func (*AnalysisServiceEvent_MoblabVmTestResponse) isAnalysisServiceEvent_Response() {}

func (m *AnalysisServiceEvent) GetResponse() isAnalysisServiceEvent_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *AnalysisServiceEvent) GetInstallPackagesResponse() *api.InstallPackagesResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_InstallPackagesResponse); ok {
		return x.InstallPackagesResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBundleResponse() *api.BundleResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_BundleResponse); ok {
		return x.BundleResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBinhostGetResponse() *api.BinhostGetResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_BinhostGetResponse); ok {
		return x.BinhostGetResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetAclArgsResponse() *api.AclArgsResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_AclArgsResponse); ok {
		return x.AclArgsResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetPrepareBinhostUploadsResponse() *api.PrepareBinhostUploadsResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_PrepareBinhostUploadsResponse); ok {
		return x.PrepareBinhostUploadsResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetSetBinhostResponse() *api.SetBinhostResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_SetBinhostResponse); ok {
		return x.SetBinhostResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetRegenBuildCacheResponse() *api.RegenBuildCacheResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_RegenBuildCacheResponse); ok {
		return x.RegenBuildCacheResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetGetBuildDependencyGraphResponse() *api.GetBuildDependencyGraphResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_GetBuildDependencyGraphResponse); ok {
		return x.GetBuildDependencyGraphResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetCreateImageResult() *api.CreateImageResult {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_CreateImageResult); ok {
		return x.CreateImageResult
	}
	return nil
}

func (m *AnalysisServiceEvent) GetTestImageResult() *api.TestImageResult {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_TestImageResult); ok {
		return x.TestImageResult
	}
	return nil
}

func (m *AnalysisServiceEvent) GetCreateResponse() *api.CreateResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_CreateResponse); ok {
		return x.CreateResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetUpdateResponse() *api.UpdateResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_UpdateResponse); ok {
		return x.UpdateResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetSysrootCreateResponse() *api.SysrootCreateResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_SysrootCreateResponse); ok {
		return x.SysrootCreateResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetInstallToolchainResponse() *api.InstallToolchainResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_InstallToolchainResponse); ok {
		return x.InstallToolchainResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetBuildTargetUnitTestResponse() *api.BuildTargetUnitTestResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_BuildTargetUnitTestResponse); ok {
		return x.BuildTargetUnitTestResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetChromiteUnitTestResponse() *api.ChromiteUnitTestResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_ChromiteUnitTestResponse); ok {
		return x.ChromiteUnitTestResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetDebugInfoTestResponse() *api.DebugInfoTestResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_DebugInfoTestResponse); ok {
		return x.DebugInfoTestResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetVmTestResponse() *api.VmTestResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_VmTestResponse); ok {
		return x.VmTestResponse
	}
	return nil
}

func (m *AnalysisServiceEvent) GetMoblabVmTestResponse() *api.MoblabVmTestResponse {
	if x, ok := m.GetResponse().(*AnalysisServiceEvent_MoblabVmTestResponse); ok {
		return x.MoblabVmTestResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AnalysisServiceEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AnalysisServiceEvent_InstallPackagesRequest)(nil),
		(*AnalysisServiceEvent_BundleRequest)(nil),
		(*AnalysisServiceEvent_BundleVmFilesRequest)(nil),
		(*AnalysisServiceEvent_BinhostGetRequest)(nil),
		(*AnalysisServiceEvent_AclArgsRequest)(nil),
		(*AnalysisServiceEvent_PrepareBinhostUploadsRequest)(nil),
		(*AnalysisServiceEvent_SetBinhostRequest)(nil),
		(*AnalysisServiceEvent_RegenBuildCacheRequest)(nil),
		(*AnalysisServiceEvent_GetBuildDependencyGraphRequest)(nil),
		(*AnalysisServiceEvent_CreateImageRequest)(nil),
		(*AnalysisServiceEvent_TestImageRequest)(nil),
		(*AnalysisServiceEvent_CreateRequest)(nil),
		(*AnalysisServiceEvent_UpdateRequest)(nil),
		(*AnalysisServiceEvent_SysrootCreateRequest)(nil),
		(*AnalysisServiceEvent_InstallToolchainRequest)(nil),
		(*AnalysisServiceEvent_BuildTargetUnitTestRequest)(nil),
		(*AnalysisServiceEvent_ChromiteUnitTestRequest)(nil),
		(*AnalysisServiceEvent_DebugInfoTestRequest)(nil),
		(*AnalysisServiceEvent_VmTestRequest)(nil),
		(*AnalysisServiceEvent_MoblabVmTestRequest)(nil),
		(*AnalysisServiceEvent_InstallPackagesResponse)(nil),
		(*AnalysisServiceEvent_BundleResponse)(nil),
		(*AnalysisServiceEvent_BinhostGetResponse)(nil),
		(*AnalysisServiceEvent_AclArgsResponse)(nil),
		(*AnalysisServiceEvent_PrepareBinhostUploadsResponse)(nil),
		(*AnalysisServiceEvent_SetBinhostResponse)(nil),
		(*AnalysisServiceEvent_RegenBuildCacheResponse)(nil),
		(*AnalysisServiceEvent_GetBuildDependencyGraphResponse)(nil),
		(*AnalysisServiceEvent_CreateImageResult)(nil),
		(*AnalysisServiceEvent_TestImageResult)(nil),
		(*AnalysisServiceEvent_CreateResponse)(nil),
		(*AnalysisServiceEvent_UpdateResponse)(nil),
		(*AnalysisServiceEvent_SysrootCreateResponse)(nil),
		(*AnalysisServiceEvent_InstallToolchainResponse)(nil),
		(*AnalysisServiceEvent_BuildTargetUnitTestResponse)(nil),
		(*AnalysisServiceEvent_ChromiteUnitTestResponse)(nil),
		(*AnalysisServiceEvent_DebugInfoTestResponse)(nil),
		(*AnalysisServiceEvent_VmTestResponse)(nil),
		(*AnalysisServiceEvent_MoblabVmTestResponse)(nil),
	}
}

func init() {
	proto.RegisterType((*AnalysisServiceEvent)(nil), "analysis_service.AnalysisServiceEvent")
}

func init() {
	proto.RegisterFile("analysis_service/analysis_service.proto", fileDescriptor_92c22ab0fbdfe575)
}

var fileDescriptor_92c22ab0fbdfe575 = []byte{
	// 1185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0x6b, 0x6f, 0xdb, 0x36,
	0x17, 0xc7, 0x1f, 0x3f, 0xdd, 0x9a, 0x84, 0xb9, 0x33, 0x6e, 0xac, 0xd8, 0x49, 0xec, 0x26, 0xbd,
	0xa4, 0xed, 0xe6, 0x00, 0xdb, 0xeb, 0x61, 0xc8, 0xa5, 0x4b, 0x82, 0x61, 0x45, 0xe7, 0x24, 0xc5,
	0xb0, 0x62, 0xd3, 0x28, 0x89, 0x56, 0x88, 0xea, 0x56, 0x91, 0x32, 0x90, 0x01, 0xfb, 0x98, 0xfb,
	0x3e, 0x03, 0x29, 0x8a, 0x14, 0x65, 0xda, 0xcd, 0x4b, 0x9f, 0x73, 0xf8, 0xfb, 0x1f, 0x91, 0x87,
	0xfc, 0x27, 0xe0, 0x25, 0x4a, 0x50, 0x74, 0x4f, 0x09, 0x75, 0x29, 0xce, 0x27, 0xc4, 0xc7, 0xc7,
	0xcd, 0xc0, 0x30, 0xcb, 0x53, 0x96, 0xc2, 0x8d, 0x66, 0xbc, 0xbb, 0xeb, 0xdf, 0xe5, 0x69, 0x4c,
	0x18, 0x3e, 0x46, 0x19, 0x39, 0x46, 0x39, 0x23, 0x63, 0xe4, 0x33, 0x5a, 0xd6, 0x77, 0xbb, 0x46,
	0xd6, 0x23, 0xc9, 0x5d, 0x4a, 0x99, 0xcc, 0xf5, 0x8c, 0x5c, 0x80, 0xb3, 0x30, 0x47, 0xd9, 0x9d,
	0x4c, 0x3a, 0x46, 0x92, 0xc4, 0x28, 0x94, 0x2d, 0x74, 0xb7, 0x8d, 0x0c, 0x0d, 0x3e, 0x59, 0xa5,
	0xe8, 0x3d, 0xcd, 0xd3, 0xb4, 0x92, 0xea, 0x18, 0x39, 0x86, 0x55, 0x0f, 0xfd, 0x30, 0x4d, 0xc3,
	0x08, 0x1f, 0x8b, 0x5f, 0x5e, 0x31, 0x3e, 0x66, 0x24, 0xc6, 0x94, 0xa1, 0x38, 0x2b, 0x0b, 0x0e,
	0xfe, 0xdd, 0x03, 0xed, 0x13, 0xf9, 0xcd, 0xd7, 0xe5, 0x27, 0xbf, 0x9d, 0xe0, 0x84, 0xc1, 0x1d,
	0xb0, 0xe8, 0x15, 0x24, 0x0a, 0x5c, 0x12, 0x38, 0xaf, 0x07, 0xad, 0xa3, 0x47, 0xa3, 0x05, 0xf1,
	0xfb, 0x2a, 0x80, 0x3d, 0xb0, 0x44, 0x19, 0xce, 0xdc, 0x04, 0xc5, 0xd8, 0x79, 0x33, 0x68, 0x1d,
	0x2d, 0x8d, 0x16, 0x79, 0xe0, 0x1d, 0x8a, 0x31, 0xfc, 0x01, 0xac, 0xe4, 0xf8, 0x73, 0x81, 0x29,
	0x73, 0xb9, 0x96, 0xf3, 0x68, 0xd0, 0x3a, 0x5a, 0xfe, 0xae, 0x3b, 0x2c, 0x1b, 0x19, 0x56, 0x8d,
	0x0c, 0x6f, 0xaa, 0x46, 0x46, 0xcb, 0xb2, 0x9e, 0x47, 0xe0, 0x8f, 0x60, 0x35, 0xc7, 0x34, 0x4b,
	0x13, 0x8a, 0xcb, 0xf5, 0x5f, 0x7d, 0x71, 0xfd, 0x4a, 0xb5, 0x40, 0x00, 0xfe, 0x02, 0x0e, 0x49,
	0x28, 0x43, 0x51, 0xe4, 0x66, 0xc8, 0xff, 0x84, 0x42, 0x4c, 0x5d, 0x29, 0xe0, 0xb4, 0x04, 0xeb,
	0xd9, 0xb0, 0xda, 0xad, 0x21, 0xca, 0xc8, 0xf0, 0xaa, 0xac, 0x7e, 0x2f, 0x8b, 0x47, 0x65, 0xed,
	0xe5, 0xff, 0x46, 0xdb, 0xc4, 0x9a, 0x81, 0xe7, 0x60, 0xcd, 0x2b, 0x92, 0x20, 0xc2, 0x8a, 0xfb,
	0xb5, 0xe0, 0xf6, 0x4c, 0xee, 0xa9, 0xa8, 0xd1, 0xb8, 0x55, 0xaf, 0x1e, 0x80, 0x1f, 0x41, 0x47,
	0x52, 0x26, 0xb1, 0x3b, 0x26, 0x51, 0xad, 0xcd, 0x05, 0x81, 0x3b, 0xb0, 0xe1, 0x3e, 0xc4, 0x3f,
	0xf1, 0x52, 0x4d, 0x6d, 0x7b, 0x96, 0x38, 0xfc, 0x15, 0x6c, 0xc9, 0x59, 0x74, 0x43, 0xcc, 0x14,
	0x78, 0x51, 0x80, 0xfb, 0x0d, 0x70, 0x59, 0x78, 0x81, 0x99, 0xa6, 0x6e, 0x7a, 0xcd, 0x20, 0xbc,
	0x04, 0x1b, 0xc8, 0x8f, 0x5c, 0x94, 0x87, 0xba, 0x51, 0x20, 0x78, 0xbb, 0x26, 0xef, 0xc4, 0x8f,
	0x4e, 0xf2, 0xb0, 0xd6, 0xe2, 0x1a, 0x32, 0x22, 0x90, 0x82, 0x7e, 0x96, 0xe3, 0x0c, 0xe5, 0xd8,
	0xad, 0x9a, 0x2c, 0xb2, 0x28, 0x45, 0x81, 0x06, 0xaf, 0x08, 0xf0, 0x6b, 0x13, 0xfc, 0xbe, 0x5c,
	0x24, 0xfb, 0xbd, 0x2d, 0x97, 0x68, 0x99, 0xdd, 0x6c, 0x4e, 0x9e, 0xef, 0x08, 0xc5, 0x4c, 0x09,
	0x56, 0x42, 0x6b, 0xb6, 0x1d, 0xb9, 0xc6, 0x4c, 0x42, 0x6a, 0x3b, 0x42, 0x9b, 0x41, 0x88, 0xc0,
	0x4e, 0x8e, 0x43, 0x9c, 0xb8, 0xe5, 0x3d, 0xf1, 0x91, 0x7f, 0xa7, 0x47, 0x62, 0xc3, 0x36, 0x6a,
	0x23, 0x5e, 0x7e, 0xca, 0xab, 0xcf, 0x78, 0x71, 0x6d, 0xd4, 0x72, 0x6b, 0x06, 0xfe, 0x0d, 0x0e,
	0xf8, 0xf9, 0x95, 0x02, 0x01, 0xce, 0x70, 0x12, 0xe0, 0xc4, 0xbf, 0x77, 0xc5, 0x4b, 0xa2, 0xb4,
	0xa0, 0xd0, 0xfa, 0xc6, 0xd4, 0xba, 0xc0, 0x4c, 0xf0, 0xce, 0xd5, 0xaa, 0x0b, 0xbe, 0x48, 0x6b,
	0xee, 0x87, 0x73, 0x2b, 0xe0, 0x0d, 0x68, 0xfb, 0x39, 0x46, 0x0c, 0xbb, 0xe2, 0x75, 0x52, 0x6a,
	0x6d, 0xa1, 0x36, 0x30, 0xd5, 0xce, 0x44, 0xe5, 0x15, 0x2f, 0xd4, 0x0a, 0xd0, 0x9f, 0x8a, 0xc2,
	0x77, 0x00, 0xf2, 0xe7, 0xa9, 0xc1, 0xdc, 0x16, 0xcc, 0x7d, 0x93, 0x79, 0x83, 0x29, 0x6b, 0x10,
	0x37, 0x58, 0x23, 0xc6, 0x2f, 0xa3, 0xec, 0xb2, 0x62, 0x39, 0xb6, 0xcb, 0x58, 0xf6, 0x57, 0xbb,
	0x8c, 0x7e, 0x3d, 0xc0, 0x29, 0x45, 0x16, 0xd4, 0x29, 0x5d, 0x1b, 0xe5, 0x56, 0xd4, 0xd4, 0x28,
	0x45, 0x3d, 0x00, 0x7f, 0x07, 0xdb, 0xf2, 0x59, 0x76, 0x1b, 0x3d, 0xed, 0xda, 0x6e, 0xf4, 0x75,
	0x59, 0xdb, 0x6c, 0xad, 0x4d, 0x2d, 0x71, 0xe8, 0x83, 0x9d, 0xea, 0x59, 0x63, 0x69, 0x1a, 0xf9,
	0x77, 0x88, 0x24, 0x0a, 0xbf, 0x2f, 0xf0, 0xcf, 0xad, 0xef, 0xda, 0x4d, 0x55, 0xad, 0x15, 0x3a,
	0xc4, 0x9e, 0x82, 0x09, 0xd8, 0x2f, 0x47, 0x8d, 0xa1, 0x9c, 0xcf, 0x5d, 0x91, 0x10, 0xe6, 0x8a,
	0xe3, 0xaa, 0x94, 0x06, 0x42, 0xe9, 0xa8, 0xf9, 0x34, 0x91, 0x28, 0xb8, 0x11, 0x4b, 0x6e, 0x13,
	0xc2, 0xf8, 0xb9, 0x69, 0xb1, 0xae, 0x37, 0x33, 0x0b, 0x03, 0xa0, 0x4c, 0xcd, 0xa2, 0x75, 0x60,
	0xfb, 0xaa, 0x33, 0xf9, 0x63, 0x5a, 0x48, 0x79, 0x60, 0x53, 0xe5, 0x23, 0xe8, 0x04, 0xd8, 0x2b,
	0x42, 0x97, 0x24, 0xe3, 0xd4, 0x94, 0x78, 0x66, 0x3b, 0x97, 0x73, 0x5e, 0x7c, 0x95, 0x8c, 0x53,
	0x93, 0xdf, 0x0e, 0x2c, 0x71, 0xf8, 0x16, 0xac, 0x4f, 0x62, 0x13, 0xfa, 0xc2, 0x36, 0x3a, 0x1f,
	0x62, 0x93, 0xb6, 0x3a, 0xa9, 0x07, 0xe0, 0x6f, 0x60, 0x3b, 0x4e, 0xbd, 0x08, 0x79, 0x6e, 0x93,
	0x76, 0x24, 0x68, 0x4f, 0x4d, 0xda, 0x2f, 0xa2, 0xb6, 0xc9, 0xdc, 0x8a, 0xa7, 0xc3, 0xf5, 0xc1,
	0xa9, 0xf9, 0x61, 0x69, 0x98, 0xce, 0xff, 0xe7, 0x0c, 0x8e, 0xb6, 0xbd, 0xb2, 0xf8, 0xb2, 0xa5,
	0x06, 0xa7, 0x99, 0x82, 0x17, 0x60, 0x5d, 0x59, 0xa2, 0x44, 0x3f, 0xb6, 0x79, 0x43, 0xe5, 0x89,
	0x8a, 0xb8, 0xe6, 0x19, 0x11, 0xfe, 0xe8, 0x98, 0xc6, 0x25, 0x69, 0x4b, 0xb6, 0x47, 0xa7, 0xee,
	0x5c, 0x8a, 0x08, 0xbd, 0xa9, 0x28, 0xfc, 0x19, 0x6c, 0xd6, 0xbc, 0x4b, 0x22, 0x97, 0x05, 0x72,
	0x6f, 0x86, 0x79, 0x29, 0xde, 0x3a, 0x32, 0x43, 0x70, 0x02, 0x06, 0xb3, 0xed, 0x4b, 0xb2, 0x57,
	0x05, 0xfb, 0xcd, 0x83, 0xfc, 0x4b, 0x29, 0xed, 0x65, 0xf3, 0x0a, 0xf8, 0xd6, 0x98, 0x0e, 0x26,
	0xb5, 0xd6, 0x6d, 0x5b, 0x53, 0xb7, 0x30, 0xbd, 0x35, 0x74, 0x2a, 0xca, 0xaf, 0xa0, 0xcd, 0xc4,
	0x24, 0x7b, 0xd3, 0x36, 0x1f, 0x53, 0x2e, 0xa6, 0xe7, 0x23, 0xb7, 0xa7, 0xe0, 0x3f, 0xe0, 0x70,
	0xae, 0x8f, 0x49, 0xb9, 0x2d, 0x21, 0xf7, 0xed, 0x03, 0x8d, 0x4c, 0xc9, 0xf6, 0xc3, 0xf9, 0x25,
	0xdc, 0xfc, 0x1b, 0x56, 0x46, 0x8b, 0x88, 0x39, 0x4f, 0x6c, 0xe6, 0x6f, 0x38, 0x19, 0x2f, 0xbb,
	0x6c, 0x8d, 0x36, 0xfd, 0x66, 0x90, 0x8f, 0x94, 0xe1, 0x63, 0x02, 0xd8, 0xb1, 0x8d, 0x54, 0xcd,
	0xc6, 0x24, 0x6e, 0x9d, 0x99, 0x21, 0x7e, 0x7d, 0x94, 0x61, 0xc8, 0xad, 0xd8, 0xb1, 0x5d, 0x9f,
	0xca, 0x12, 0xf4, 0xf5, 0xf1, 0x8d, 0x08, 0x07, 0x29, 0x1f, 0x93, 0xa0, 0x9e, 0x0d, 0x54, 0x19,
	0x99, 0x06, 0x15, 0x46, 0x04, 0xfe, 0x01, 0x3a, 0x53, 0x56, 0x26, 0x81, 0x7b, 0x02, 0x78, 0x38,
	0xd7, 0xcb, 0x14, 0xf7, 0x09, 0xb5, 0x25, 0xe0, 0x18, 0x74, 0x6d, 0x6e, 0x26, 0x15, 0xfa, 0x42,
	0xe1, 0xc5, 0x97, 0xec, 0x4c, 0x89, 0x38, 0x64, 0x46, 0x0e, 0x7e, 0x06, 0xfd, 0x99, 0x86, 0x26,
	0xc5, 0x9e, 0x0a, 0xb1, 0x57, 0x0f, 0x70, 0x34, 0xa5, 0xd7, 0xf3, 0x66, 0xa7, 0x61, 0x08, 0x7a,
	0x56, 0x4f, 0x93, 0x72, 0x87, 0xb6, 0x6f, 0x9b, 0x36, 0x35, 0xfd, 0x6d, 0xfe, 0x8c, 0x1c, 0xfc,
	0x13, 0x38, 0xd3, 0xb6, 0x26, 0x55, 0x9e, 0xdb, 0xce, 0xa8, 0xe1, 0x6b, 0xfa, 0x8c, 0x02, 0x5b,
	0x82, 0xff, 0xc1, 0xaf, 0xbd, 0x48, 0x72, 0x5f, 0xda, 0x86, 0xa9, 0xf2, 0x1b, 0x3d, 0x4c, 0x13,
	0x23, 0xc2, 0x0d, 0x78, 0xca, 0xdc, 0x24, 0xf0, 0x95, 0xcd, 0x80, 0x4d, 0x77, 0x53, 0xd8, 0x76,
	0x6c, 0x89, 0x9f, 0x2e, 0x81, 0x05, 0x69, 0x95, 0xa7, 0x00, 0x2c, 0x56, 0x60, 0xef, 0xb1, 0xf8,
	0x47, 0xf1, 0xfb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x23, 0xb6, 0x11, 0x17, 0xfa, 0x0f, 0x00,
	0x00,
}
