// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_platform/steps/enumeration.proto

package steps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	test_platform "go.chromium.org/chromiumos/infra/proto/go/test_platform"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EnumerationRequest defines the input of the test enumeration step.
type EnumerationRequest struct {
	Metadata             *test_platform.Request_Params_Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TestPlan             *test_platform.Request_TestPlan        `protobuf:"bytes,4,opt,name=test_plan,json=testPlan,proto3" json:"test_plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *EnumerationRequest) Reset()         { *m = EnumerationRequest{} }
func (m *EnumerationRequest) String() string { return proto.CompactTextString(m) }
func (*EnumerationRequest) ProtoMessage()    {}
func (*EnumerationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e663b0bcf1c9d2c, []int{0}
}

func (m *EnumerationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerationRequest.Unmarshal(m, b)
}
func (m *EnumerationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerationRequest.Marshal(b, m, deterministic)
}
func (m *EnumerationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerationRequest.Merge(m, src)
}
func (m *EnumerationRequest) XXX_Size() int {
	return xxx_messageInfo_EnumerationRequest.Size(m)
}
func (m *EnumerationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerationRequest proto.InternalMessageInfo

func (m *EnumerationRequest) GetMetadata() *test_platform.Request_Params_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EnumerationRequest) GetTestPlan() *test_platform.Request_TestPlan {
	if m != nil {
		return m.TestPlan
	}
	return nil
}

// EnumerationResponse defines the output of the test enumeration step.
type EnumerationResponse struct {
	AutotestInvocations  []*EnumerationResponse_AutotestInvocation `protobuf:"bytes,2,rep,name=autotest_invocations,json=autotestInvocations,proto3" json:"autotest_invocations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *EnumerationResponse) Reset()         { *m = EnumerationResponse{} }
func (m *EnumerationResponse) String() string { return proto.CompactTextString(m) }
func (*EnumerationResponse) ProtoMessage()    {}
func (*EnumerationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e663b0bcf1c9d2c, []int{1}
}

func (m *EnumerationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerationResponse.Unmarshal(m, b)
}
func (m *EnumerationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerationResponse.Marshal(b, m, deterministic)
}
func (m *EnumerationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerationResponse.Merge(m, src)
}
func (m *EnumerationResponse) XXX_Size() int {
	return xxx_messageInfo_EnumerationResponse.Size(m)
}
func (m *EnumerationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerationResponse proto.InternalMessageInfo

func (m *EnumerationResponse) GetAutotestInvocations() []*EnumerationResponse_AutotestInvocation {
	if m != nil {
		return m.AutotestInvocations
	}
	return nil
}

type EnumerationResponse_AutotestInvocation struct {
	Test                 *api.AutotestTest `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	TestArgs             string            `protobuf:"bytes,2,opt,name=test_args,json=testArgs,proto3" json:"test_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EnumerationResponse_AutotestInvocation) Reset() {
	*m = EnumerationResponse_AutotestInvocation{}
}
func (m *EnumerationResponse_AutotestInvocation) String() string { return proto.CompactTextString(m) }
func (*EnumerationResponse_AutotestInvocation) ProtoMessage()    {}
func (*EnumerationResponse_AutotestInvocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e663b0bcf1c9d2c, []int{1, 0}
}

func (m *EnumerationResponse_AutotestInvocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerationResponse_AutotestInvocation.Unmarshal(m, b)
}
func (m *EnumerationResponse_AutotestInvocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerationResponse_AutotestInvocation.Marshal(b, m, deterministic)
}
func (m *EnumerationResponse_AutotestInvocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerationResponse_AutotestInvocation.Merge(m, src)
}
func (m *EnumerationResponse_AutotestInvocation) XXX_Size() int {
	return xxx_messageInfo_EnumerationResponse_AutotestInvocation.Size(m)
}
func (m *EnumerationResponse_AutotestInvocation) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerationResponse_AutotestInvocation.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerationResponse_AutotestInvocation proto.InternalMessageInfo

func (m *EnumerationResponse_AutotestInvocation) GetTest() *api.AutotestTest {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *EnumerationResponse_AutotestInvocation) GetTestArgs() string {
	if m != nil {
		return m.TestArgs
	}
	return ""
}

func init() {
	proto.RegisterType((*EnumerationRequest)(nil), "test_platform.steps.EnumerationRequest")
	proto.RegisterType((*EnumerationResponse)(nil), "test_platform.steps.EnumerationResponse")
	proto.RegisterType((*EnumerationResponse_AutotestInvocation)(nil), "test_platform.steps.EnumerationResponse.AutotestInvocation")
}

func init() {
	proto.RegisterFile("test_platform/steps/enumeration.proto", fileDescriptor_2e663b0bcf1c9d2c)
}

var fileDescriptor_2e663b0bcf1c9d2c = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x16, 0x69, 0xb7, 0xb7, 0xad, 0x87, 0x92, 0x1e, 0x2c, 0x05, 0xa5, 0xa7, 0x5d,
	0xa8, 0x47, 0x15, 0x69, 0xc1, 0x83, 0x07, 0xa1, 0x04, 0x4f, 0x5e, 0x64, 0xac, 0xdb, 0x18, 0x68,
	0x76, 0xd6, 0x9d, 0x89, 0x8f, 0xe2, 0x33, 0xfa, 0x18, 0xd2, 0xcd, 0xa6, 0x12, 0x1a, 0x6f, 0xc9,
	0x7c, 0xdf, 0xfc, 0xe6, 0xdf, 0x8a, 0x4b, 0x36, 0xc4, 0xaf, 0x6e, 0x07, 0xbc, 0x45, 0x5f, 0x6a,
	0x62, 0xe3, 0x48, 0x1b, 0x5b, 0x95, 0xc6, 0x03, 0x17, 0x68, 0x95, 0xf3, 0xc8, 0x28, 0x47, 0x2d,
	0x9b, 0x0a, 0xb6, 0x74, 0xba, 0xf9, 0xf0, 0x58, 0x16, 0x6c, 0x34, 0xb8, 0x42, 0x07, 0x47, 0x69,
	0x18, 0xde, 0x81, 0xa1, 0x4e, 0x4b, 0x27, 0x6d, 0xba, 0x37, 0x9f, 0x95, 0x21, 0xae, 0xc5, 0xd9,
	0x77, 0x22, 0xe4, 0xc3, 0x5f, 0xa5, 0xac, 0x16, 0xe5, 0x4a, 0xf4, 0x1b, 0xca, 0x38, 0x99, 0x26,
	0xf3, 0xe1, 0xe2, 0x4a, 0xb5, 0xab, 0x47, 0xa7, 0x5a, 0x83, 0x87, 0x92, 0xd4, 0x53, 0x74, 0x67,
	0x87, 0x3c, 0x79, 0x2b, 0x06, 0x4d, 0x8a, 0x1d, 0xf7, 0x02, 0xe4, 0xe2, 0x1f, 0xc8, 0xb3, 0x21,
	0x5e, 0xef, 0xc0, 0x66, 0x7d, 0x8e, 0x5f, 0xb3, 0x9f, 0x44, 0x8c, 0x5a, 0x8d, 0x91, 0x43, 0x4b,
	0x46, 0x5a, 0x71, 0x0e, 0x15, 0x63, 0xe0, 0x14, 0xf6, 0x0b, 0x37, 0x41, 0xa6, 0xf1, 0xc9, 0xf4,
	0x74, 0x3e, 0x5c, 0xdc, 0xa8, 0x8e, 0x1d, 0xa9, 0x0e, 0x8e, 0x5a, 0x46, 0xc8, 0xe3, 0x81, 0x91,
	0x8d, 0xe0, 0x28, 0x46, 0x29, 0x08, 0x79, 0x6c, 0x95, 0x4a, 0xf4, 0xf6, 0x91, 0xb8, 0x9b, 0x54,
	0x35, 0x47, 0x50, 0xe0, 0x8a, 0x03, 0x7a, 0x3f, 0x55, 0x16, 0x7c, 0x72, 0x12, 0x77, 0x01, 0x3e,
	0xdf, 0xb7, 0x9a, 0xcc, 0x07, 0xf5, 0xa8, 0x4b, 0x9f, 0xd3, 0xea, 0xfe, 0xe5, 0x2e, 0xc7, 0x88,
	0xa8, 0x4a, 0x85, 0x3e, 0xd7, 0xcd, 0x0f, 0x92, 0x2e, 0xec, 0xd6, 0x83, 0x0e, 0xd7, 0xd2, 0x39,
	0xea, 0x8e, 0xa7, 0xf2, 0x76, 0x16, 0xd4, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x63,
	0x54, 0x0c, 0x48, 0x02, 0x00, 0x00,
}
