// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

message Presence {
  enum Indicator {
    PRESENCE_UNKNOWN = 0;
    PRESENT = 1;
    NOT_PRESENT = 2;
  }
}

message ByteSize {
  enum Unit {
    UNIT_UNDEFINED = 0;
    BYTE = 1;
    KB = 2;
    MB = 3;
    GB = 4;
  }

  int32 value = 1;
  Unit unit = 2;
}

message UsbDeviceId {
  uint32 vendor_id = 1;
  uint32 product_id = 2;
  uint32 bcd_device = 3;
}
