// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

import "prototype/partner.proto";

import "google/protobuf/descriptor.proto";

message ComponentId {
  string value = 1;
}

message ByteSize {
  enum Unit {
    UNIT_UNDEFINED = 0;
    BYTE = 1;
    KB = 2;
    MB = 3;
    GB = 4;
  }

  int32 value = 1;
  Unit unit = 2;
}

message Soc {
  enum Architecture {
    ARCHITECTURE_UNDEFINED = 0;
    X86 = 1;
    X86_64 = 2;
    ARM = 3;
    ARM64 = 4;
  }

  extend google.protobuf.EnumValueOptions {
    Architecture arch = 1914502;
  }

  enum Family {
    FAMILY_UNDEFINED = 0;
    RK3399 = 1 [(arch) = ARM64];
    GEMINI_LAKE = 2 [(arch) = X86_64];
  }

  message Component {
    Family family = 1;
    string model = 2;
    int32 cores = 3;
  }

  message Constraint {
    repeated ComponentId soc_models = 1;
  }
}

message Memory {
  enum Type {
    TYPE_UNDEFINED = 0;
    DDR = 1;
    DDR2 = 2;
    DDR3 = 3;
    DDR4 = 4;
    LP_DDR3 = 5;
    LP_DDR4 = 6;
  }

  message Component {
    Type type = 1;
    int32 speed_mhz = 2;
    ByteSize size = 3;
    string part_number = 4;
    PartnerId manufacturer_id = 5;
  }

  message Constraint {
    ByteSize min_size = 1;
    repeated Type types = 2;
  }
}

message UsbDeviceId {
  uint32 vendor_id = 1;
  uint32 product_id = 2;
  uint32 bcd_device = 3;
}

message Bluetooth {
  message Component {
    UsbDeviceId usb_device_id = 1;
  }

  message Constraint {
    repeated ComponentId bluetooth_devices = 1;
  }
}

message Component {
  ComponentId id = 1;

  oneof type {
    Soc.Component soc = 2;
    Memory.Component memory = 3;
    Bluetooth.Component bluetooth = 4;
  }
}

message ComponentList {
  repeated Component value = 1;
}
