// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

import "prototype/component.proto";
import "prototype/partner.proto";
import "prototype/ref_design.proto";
import "prototype/ref_design_kit.proto";
import "prototype/device_project.proto";

import "prototype/src/third_party/chromiumos-overlay/config.proto";

message Config {
  PartnerList partners = 1;
  ComponentList components = 2;
  RefDesignKitList ref_design_kits = 3;
  RefDesignList ref_designs = 4;
  DeviceProject device_projects = 5;

  BuildTargetList build_targets = 6;
  VariantBuildConfigList variant_build_configs = 7;
}
