// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

import "prototype/partner.proto";
import "prototype/ref_design.proto";

message DeviceBrandId {
  string value = 1;
}

message DeviceBrand {
  DeviceBrandId id = 1;
  RefDesignId ref_design_id = 2;
  PartnerId oem_id = 3;
  string brand_code = 4;
  string brand_name = 5;
}

message DeviceBrandList {
  repeated DeviceBrand value = 1;
}

// Metadata around all of the logistics for the project
message DeviceProject {
  DeviceBrandId id = 1;
  string name = 2;
  string bug_component_id = 3;
}

message DeviceProjectList {
  repeated DeviceProject value = 1;
}
