// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

import "prototype/component.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

message RefDesignKitId {
  string value = 1;
}

message RefDesignKit {
  RefDesignKitId id = 1;
  repeated Requirements reqs = 2;

  enum FormFactor {
    FORM_FACTOR_UNDEFINED = 0;
    CLAMSHELL = 1;
    CONVERTIBLE = 2;
    DETACHABLE = 3;
    CHROMEBASE = 4;
    CHROMEBOX = 5;
    CHROMEBIT = 6;
    CHROMESLATE = 7;
  }

  message Requirements {
    FormFactor form_factor = 1;
    Soc.Constraint soc = 2;
    Memory.Constraint memory = 3;
  }
}

message RefDesignKitList {
  repeated RefDesignKit value = 1;
}
