// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package prototype;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/prototype";

import "prototype/common.proto";
import "prototype/partner.proto";

message RefDesignKitId {
  string value = 1;
}

message RefDesignId {
  string value = 1;
}

message RefDesignVariantId {
  string value = 1;
}

message DesignOptions {
  Fingerprint fingerprint = 1;
  Camera front_camera = 2;
  Camera rear_camera = 3;

  message Fingerprint {
    enum Location {
      FINGERPRINT_LOCATION_UKNOWN = 0;
      POWER_BUTTON_TOP_LEFT = 1;
      KEYBOARD_TOP_RIGHT = 2;
      KEYBOARD_BOTTOM_RIGHT = 3;
    }
    Presence presence = 1;
    Location location = 2;
  }

  message Camera {
    Presence presence = 1;
  }
}

message RefDesign {
  RefDesignId id = 1;
  RefDesignKitId ref_design_kit_id = 2;
  PartnerId odm_id = 3;
  string name = 4;

  repeated Variant variants = 6;

  message Variant {
    RefDesignVariantId id = 1;
    FormFactor form_factor = 2;
    DesignOptions design_options = 3;
  }

  enum FormFactor {
    FORM_FACTOR_UNDEFINED = 0;
    CLAMSHELL = 1;
    CONVERTIBLE = 2;
    DETACHABLE = 3;
    CHROMEBASE = 4;
    CHROMEBOX = 5;
    CHROMEBIT = 6;
    CHROMESLATE = 7;
  }
}

message RefDesignList {
  repeated RefDesign value = 1;
}
