// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.skylab_local_state;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_state";

import "test_platform/skylab_local_state/common.proto";

// LoadRequest defines the input of `skylab_local_state load`.
message LoadRequest {
  Config config = 1;

  // The path to the directory where the host info file will be placed. It will
  // be created it if does not exist yet.
  string results_dir = 2;

  // DUT hostname.
  string dut_name = 3;

  string dut_id = 4 [deprecated = true];
}

// LoadResponse defines the output of `skylab_local_state load`.
message LoadResponse {
  // What is currently installed on the DUT, e.g.
  // "cros-version": "reef-release/R77-12345.0.0".
  map<string, string> provisionable_labels = 1;

  string dut_name = 2 [deprecated = true];
}
