// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.skylab_local_state;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/skylab_local_state";

// Config defines configuration parameters of skylab_local_state.
message Config {
  // Admin service host, e.g. foo.appspot.com.
  string admin_service = 1;
}

// LoadRequest defines the input of `skylab_local_state load`.
message LoadRequest {
  Config config = 1;

  // The path to the directory where the host info file will be placed. It will
  // be created it if does not exist yet.
  string results_dir = 2;

  // skylab_inventory ID of the DUT.
  string dut_id = 3;
}

// LoadResponse defines the output of `skylab_local_state load`.
message LoadResponse {
  // DUT hostname.
  string dut_name = 1;

  // What is currently installed on the DUT, e.g.
  // "cros-version": "reef-release/R77-12345.0.0".
  map<string, string> provisionable_labels = 2;
}
