// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab";

import "device/config_id.proto";
import "lab/chromeos_device_id.proto";
import "lab/peripherals.proto";
import "lab/servo.proto";
import "manufacturing/config_id.proto";

// Next Tag: 7
message ChromeOSDevice {
  // A unique ID for chromeos device, a randomly generated uuid or AssetTag.
  ChromeOSDeviceID id = 1;
  string serial_number = 2;
  manufacturing.ConfigID manufacturing_id = 3;
  // Device config identifiers.
  // These values will be extracted from DUT and joinable to device config.
  device.ConfigId device_config_id = 4;

  oneof device {
    DeviceUnderTest dut = 5;
    Labstation labstation = 6;
  };
}

// Next Tag: 3
message DeviceUnderTest{
  string hostname = 1;
  Peripherals peripherals = 2;
}

// Next Tag: 3
message Labstation {
  string hostname = 1;
  repeated Servo servos = 2;
}