// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab";

import "device/config_id.proto";
import "lab/device_id.proto";

// Next Tag: 6
message DeviceIdentifiers {
  DeviceID device_id = 1;
  string hostname = 2;
  string hardware_id = 3;
  string serial_number = 4;

  // Device config identifiers.
  // These values will be extracted from DUT and joinable to device config.
  device.ConfigId device_config_id = 5;
}
