// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab";

// Next Tag: 3
message ManufacturingPhase {
  DevicePhase device_phase = 1;
  CR50Phase cr50_phase = 2;
}

// phases for devices. NEXT TAG: 9
enum DevicePhase {
  PHASE_INVALID = 0;
  PHASE_EVT = 1;
  PHASE_EVT2 = 2;
  PHASE_DVT = 3;
  PHASE_DVT2 = 4;
  PHASE_PVT = 5;
  PHASE_PVT2 = 6;
  PHASE_PVT3 = 7;
  PHASE_MP = 8;
}

// phases for cr50 module. NEXT TAG: 3
enum CR50Phase {
  CR50_PHASE_INVALID = 0;
  CR50_PHASE_PREPVT = 1;
  CR50_PHASE_PVT = 2;
}
