// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package lab;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/lab";

import "lab/device_id.proto";

// NEXT TAG: 6
message Servo {
  DeviceID device_id = 1;

  // Servo-specific configs
  string servo_hostname = 2;
  int32 servo_port = 3;
  string servo_serial = 4;
  ServoType servo_type = 5;
}

// NEXT TAG: 4
enum ServoType {
  SERVO_UNKNOWN = 0;
  SERVO_V3 = 1;
  SERVO_V4_WITH_SERVO_MICRO = 2;
  SERVO_V4_WITH_CCD_CR50 = 3;
}
