// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package device;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/device";

import "device/config_id.proto";

// These are the distinct configs combinations that will constitue a ChromeOS
// device.
message Config {

  // Required. Unique ID of the device config.
  ConfigId id = 1;

  // TODO(nednguyen): add the flatten list of device attributes here, e.g:
  // bluetooth, form factor, architecture, soc, partner,...
}
