// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.execution;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/execution";

import "chromiumos/build/api/container_metadata.proto";

// Uniformly applied parameters for all test executions in a test platform
// request.
message Param {
  // If set, crash reports generated during test execution are uploaded to a
  // builder-determined crash server (e.g. http://crash or
  // http://crash-staging)
  bool upload_crashes = 1;

  // If set with proper flag, CFT test execution workflow will be
  // invoked with provided container metadata.
  chromiumos.build.api.ContainerMetadata container_metadata = 2;

  // If set, a Docker container to use to run autoserv. The container must
  // contain autoserv under the same path as the host (e.g.
  // "/usr/local/autotest/server/autoserv").
  //
  // The container will be pulled if needed.
  // TODO(b/227666105): Will be deprecated once CFT workflow is enabled and
  // stable.
  chromiumos.build.api.ContainerImageInfo container_image_info = 8;
}
