// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Define a schema for debugging events in  SuiteScheduler V1.5.

syntax = "proto3";

package test_platform.suite_scheduler.v15;

import "google/protobuf/timestamp.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/suite_scheduler/v15";

// UID is wrapped message to signifiy that the value of the field should be of a
// UID type and not just a regular string. Ideally this field would be set as
// required but proto3 removed this feature from its syntax.
message UID { string id = 1; }

enum DecisionType {
  // UNKNOWN is the null option for the enum. If this decision is reached then
  // it should be treated as an error and handled accordingly.
  UNKNOWN = 0;
  SCHEDULED = 1;
  BUILD_NOT_FOUND = 3;
  NO_PASSING_BUILD = 4;
}

message SchedulingDecision {
  DecisionType type = 1;
  // If scheduled this will be false, for all other types this will be false.
  bool scheduled = 2;

  // failed_reason contains a short snippet of why the decsion was made. E.g.
  // BUILD_NOT_FOUND -> Build R120-X-X was not found in 'ABC'.
  string failed_reason = 3;
}

message SchedulingEvent {
  // run_uid is the unique identifier of the SuiteScheduler run.
  UID run_uid = 1;

  // event_uid is the unique identifier of the event being described.
  UID event_uid = 2;

  // config_name is the name of the SuiteScheduler name, not the name of the
  // test suite being ran.
  string config_name = 3;

  // suite_name is the name of the test suite being ran
  string suite_name = 4;

  // event_time is captured once a choice, to schedule or not, was made.
  google.protobuf.Timestamp event_time = 5;

  SchedulingDecision decision = 6;

  // If the config led to a a scheduled suite, attach all bbid's that were fired
  // off as a result.
  repeated int64 bbids = 7;
}