// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.v2;

import "chromiumos/common.proto";
import "chromiumos/test/api/coverage_rule.proto";
import "chromiumos/test/api/provision_state.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/v2";

// A hardware test spec simply pairs testing CoverageRules with information
// on the required provisioning state.
//
message HWTestSpec {
  // For multi-dut support (see: go/skylab-multiduts-design), we support
  // specifying multiple attr-model and attr-board attributes in the CoverageRules
  // to target compound scheduling units.
  //
  // The user may specify multiple attr-board attributes, or multiple attr-model
  // attributes or both.  If both, the number of each attribute must match:
  //
  // valid:
  //   1. [{'attr-board': 'eve'},    {'attr-board': 'eve'}]
  //   2. [{'attr-model': 'drobit'}, {'attr-model': 'dalboz'}]
  //
  //   3. [{'attr-board': 'eve'},    {'attr-board': 'eve'},
  //       {'attr-model': 'drobit'}, {'attr-model': 'dalboz'}]
  //
  // invalid:
  //   4. [{'attr-board': 'eve'}, {'attr-board': 'eve'}, { 'attr-model': 'dalboz'}]
  //
  // The board and model labels are merged to form compound labels for the
  // scheduling backend.  For multi-dut support, we have to append a numeric
  // identifer to satisfy constraints in the scheduling backend.
  //
  // Examples of the compound labels formed from above:
  //   1.  attr-board: eve|eve2
  //   2.  attr-model: drobit|dalboz
  //   3.  attr-board: eve|eve2
  //       attr-model: drobit|dalboz
  //
  chromiumos.test.api.CoverageRule coverage_rule = 1;
  repeated chromiumos.test.api.ProvisionState provision_states = 2;
}


message TestSpec {
  // Optionally override build directory path given in Request
  chromiumos.GcsPath build_directory = 1;

  oneof spec {
    HWTestSpec hw_test_spec = 2;
    // VM testing tbd
  }
}


message Request {
  // Required, specify the path to a GCS folder containing build artifacts
  chromiumos.GcsPath build_directory = 1;

  // One or more test specs to execute
  repeated TestSpec test_specs = 2;

  // Once client profiles are implemented, these details will be subsumed
  // into a profile, but in the interim we need to able to specify pool and
  // QuotaScheduler account to use.
  message SchedulerSettings {
    string pool = 1;
    string qs_account = 2;
  }
  SchedulerSettings scheduler_settings = 3;
}