// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.v2;

import "chromiumos/test/api/coverage_rule.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/v2";

message HWTestRequestBeta {
    message TestSpec {
        // Tests to run and dut criterion for running them.
        chromiumos.test.api.CoverageRule rules = 1;

        // A coverage rule is meant to match to a schedulable unit.  With
        // multi-dut support (see go/skylab-multiduts-design), we may actually
        // specify more than one model to match against a multi-dut unit.
        //
        // To support that usage, we need to be able to specify separate
        // provisioning settings for each of the models we request.  This list
        // matches 1:1 in-order with the models specified in the coverage rule.
        //
        // TODO(smcallis): The actual provisioning message name here is TBD
        //
        // repeated ProvisionRequest provision_requests = 2;
    }

    repeated TestSpec test_specs = 1;
}

message RequestBeta {
    oneof request {
        HWTestRequestBeta hw_test_request = 1;
        // Will add VM test request later
    }
}