// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Schema for configuring firmware versions.

syntax = "proto3";

package chromiumos;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/chromiumos";
option java_package = "com.google.chrome.crosinfra.proto";

// Config for signing of a specific model.
message ModelSigningConfig {
  // Key ID to use.
  string key_id = 1; // e.g. "CROTAA"

  // Brand code for the model.
  string brand_code = 2; // e.g. "ZZCR"
}

// A single firmware version
// DEPRECATED, replaced by FirmwareArchive
message FirmwareVersion {
  // The URI at which the firmware binary can be found.
  string uri = 1;

  // SHA256 hash of the firmware binary.
  string sha256 = 2;
}

// A single firmware archive
message FirmwareArchive {
  // The URI at which the firmware archive can be found.
  string uri = 1;

  // SHA256 hash of the firmware archive.
  string sha256 = 2;
}

message CbfsTargetFirmwareArchive {
  // The archive containing the target firmware.
  FirmwareArchive archive = 1;

  // The filename of the target in CBFS
  string target_name = 2;

  // Archive is an AP FW image and the target should be extracted from its CBFS
  bool extract_from_cbfs = 3;
}

message FirmwareTargetArchive {
  oneof archive {
    FirmwareArchive fw_archive = 1;
    CbfsTargetFirmwareArchive cbfs_archive = 2;
  }
}

message FirmwareVersionInfo {
  oneof info {
    FirmwareTargetArchive ec = 1;
    FirmwareTargetArchive ap = 2;
    FirmwareTargetArchive fpmcu = 3;
    FirmwareTargetArchive ish = 4;
    FirmwareTargetArchive pdc = 5;
  }
}

message FirmwareDescriptor {
  enum ReadabilityType {
    READABILITY_TYPE_UNSPECIFIED = 0;
    RO = 1;
    RW = 2;
  }
  repeated ReadabilityType readability = 1;
  FirmwareVersionInfo fw = 2;
}

message FirmwareConfiguration { repeated FirmwareDescriptor fw_config = 1; }

// Config for a specific firmware type.
// DEPRECATED, replaced by FirmwareDescriptor
message FirmwareConfig {
  // Read-only firmware version.
  FirmwareVersion ro_firmware = 1;

  // Read-write firmware version.
  FirmwareVersion rw_firmware = 2;
}

// This is the primary object to be used for configuring firmware for a model.
message FirmwareConfigForModel {
  // Name of the model in question.
  string model = 1; // e.g. "crota"

  // Signing config for the firmware of the model.
  ModelSigningConfig signing = 2;

  // AP Firmware config.
  // DEPRECATED, replaced by FirmwareConfiguration
  FirmwareConfig ap_firmware = 3;

  // EC firmware config.
  // DEPRECATED, replaced by FirmwareConfiguration
  FirmwareConfig ec_firmware = 4;

  // AP firmware containing the EC firmware for read-write EC.
  // This is multually exclusive with ec_firmware.rw_firmware. At most one can
  // have non-empty uri.
  // DEPRECATED, replaced by FirmwareConfiguration
  FirmwareVersion ap_firmware_for_ec_rw = 5;

  // fw_config message used to contain repeated fields with information
  // representative of the device as a whole.
  FirmwareConfiguration fw_config = 6;

  // OS to pin the targets in
  enum OsType {
    OS_TYPE_UNSPECIFIED = 0;
    CROS = 1;
    ANDROID = 2;
  }
  repeated OsType os = 7;
}
