// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/chromiumos";
option java_package = "com.google.chrome.crosinfra.proto";

// AggregateGreenness is the expression of greenness of source and infra
// at a given point in time.
message AggregateGreenness {
  // Greenness specific to a target.
  message Greenness {
    // The name of the target.
    string target = 1;

    // Indication of greenness for the target in this run.
    int64 metric = 2;

    // Specifies context for greenness score if needed.
    enum Context {
      UNSPECIFIED = 0;
      // The target was not relevant.
      IRRELEVANT = 1;
    }
    Context context = 3;

    // Indication of build-only greenness for the target in this run.
    int64 build_metric = 4;
  }

  // Aggregate indication of greenness for all targets in this run.
  int64 aggregate_metric = 1;

  // List of greenness to target granularity.
  repeated Greenness target_greenness = 2;

  // Aggregate indication of build-only greenness for all targets in this run.
  int64 aggregate_build_metric = 3;
}
