// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Protocol buffer definitions for operations in the binhost lookup service.

syntax = "proto3";

package chromiumos;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/chromiumos";
option java_package = "com.google.chrome.crosinfra.proto";

// This is used by the `update_service` to update the `lookup_service` database
// with metadata related to snapshots. The `update_snapshot_data` Pub/Sub topic
// is associated with this schema definition, so messages sent to update
// snapshot data must follow this format.
// All the fields must be sent in each message.
message UpdateSnapshotDataRequest {
  // Unique sha of the snapshot.
  string snapshot_sha = 1;

  // Snapshot number.
  uint32 snapshot_num = 2;

  // Boolean to denote if the snapshot is external.
  bool external = 3;

  // Id of the annealing build that created the snapshot.
  uint64 buildbucket_id = 4;
}

// This is used by the `update_service` to update the `lookup_service` database.
// While this is primarily used to update binhost metadata, the build target
// profiles table is also updated to keep a record of all build targets and
// their associated profiles. The `update_binhost_data` Pub/Sub topic is
// associated with this schema defintion, so messages sent to update binhost
// data must follow this format.
// All the fields must be sent in each message.
message UpdateBinhostDataRequest{
  // The system Chrome OS is being built for, also known as board.
  string build_target = 1;

  // Name of the profile to use with the build_target.
  string profile = 2;

  // Sha of the snapshot associated with the binhost.
  string snapshot_sha = 3;

  // Location of the binhost object in google storage.
  string gs_uri = 4;

  // Name of the google storage bucket which contains the binhost.
  string gs_bucket_name = 5;

  // Id of the postsubmit builder that created and uploaded the binhost.
  uint64 buildbucket_id = 6;

  // Bool to indicate if this binhost contains all the binpkgs specified in the
  // packages metadata file.
  bool complete = 7;

  // Bool to indicate if the binhost is private.
  bool private = 8;
}