// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

import "testplans/common.proto";

// Configures the skipping of builds for CQ runs when the triggering CLs can't
// actually affect builds.
message BuildIrrelevanceCfg {
  // File patterns that never affect Chrome OS builds.
  // See documentation in the FilePattern message.
  repeated FilePattern irrelevant_file_patterns = 3;
}
