// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

message FilePattern {
  // Bash pattern for matching a file in the chromiumos checkout.
  // This may make use of globstar (i.e. **) notation to match against many
  // subdirectories at once. The pattern will be matched against a full
  // relative path in the chromiumos checkout.
  // e.g.
  // chromite/config/** to match anything under chromite/config/
  // **/OWNERS to match any OWNERS file
  // **/*.md to match any .md file
  // src/somefile.java to match a specific file
  string pattern = 1;
}

// Configures the skipping of builds for CQ runs when the triggering CLs can't
// actually affect builds.
message BuildIrrelevanceCfg {
  // File patterns that never affect Chrome OS builds.
  // See documentation in the FilePattern message.
  repeated FilePattern irrelevant_file_patterns = 3;
}
