// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

// A unit of the CrOS codebase. As of 2019-01, this concept maps 1-to-1 with
// "paths" in the internal and external full.xml files.
message SourceTree {
  // The path of a source tree,
  // e.g. "src/platform2" or "src/third_party/kernel/v4.19".
  string path = 1;
}

message ProtoBytes {
  bytes serialized_proto = 1;
}

message FilePattern {
  // Bash pattern for matching a file in the chromiumos checkout.
  // This may make use of globstar (i.e. **) notation to match against many
  // subdirectories at once. The pattern will be matched against a full
  // relative path in the chromiumos checkout.
  // e.g.
  // chromite/config/** to match anything under chromite/config/
  // **/OWNERS to match any OWNERS file
  // **/*.md to match any .md file
  // src/somefile.java to match a specific file
  string pattern = 1;
}
