// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

import "testplans/common.proto";

message FilterBuildsRequest {
  // Serialized buildbucket Build protos that are part of this orchestrator run.
  // See https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/build.proto
  repeated ProtoBytes buildbucket_protos = 1;

  // The manifest-internal snapshot commit hash that's being used for the current build.
  string manifest_commit = 2;
}

// The response of the Filter Builds step.
message FilterBuildsResponse {
  // List of buildbucket IDs of the builds to be tested.
  repeated int64 build_ids = 3;
}

