// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

import "chromiumos/common.proto";
import "testplans/common.proto";
import "testplans/target_test_requirements_config.proto";

message GenerateTestPlanRequest {
  // Serialized buildbucket Build protos that are part of this orchestrator run.
  // See https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/build.proto
  repeated ProtoBytes buildbucket_protos = 5;

  // Path on disk to the chromiumos repo checkout.
  string chromiumos_checkout_root = 4;

  // Path on disk to the "repo" CLI tool.
  string repo_tool_path = 6;
}

// The final test plan.
message GenerateTestPlanResponse {
  repeated TestUnit test_unit = 1;

  // TODO(seanabraham): Populate these new fields
  repeated GceTestSuite gce_test_suites = 2;
  repeated HwTestSuite hw_test_suites = 3;
  repeated MoblabVmTestSuite moblab_vm_test_suites = 4;
  repeated TastVmTestSuite tast_vm_test_suites = 5;
  repeated VmTestSuite vm_test_suites = 6;
}

// The files that should be tested in a test plan.
message BuildPayload {
  // The GS bucket in which artifacts for the build are stored, e.g.
  // gs://chromeos-image-archive
  string artifacts_gs_bucket = 1;

  // The path in the bucket in which artifacts for the build are stored, e.g.
  // eve-paladin/R73-11588.0.0-rc4
  string artifacts_gs_path = 2;
}

// Metadata for executing one test configuration for one target type.
message TestUnit {
  oneof TestCfg {
    GceTestCfg gce_test_cfg = 1;
    HwTestCfg hw_test_cfg = 2;
    MoblabVmTestCfg moblab_vm_test_cfg = 3;
    TastVmTestCfg tast_vm_test_cfg = 4;
    VmTestCfg vm_test_cfg = 5;
  }

  // The build target for this test unit.
  chromiumos.BuildTarget build_target = 8;

  // The build files provided to run this test unit.
  BuildPayload build_payload = 7;
}

// The parts of a TestSuite that are common among all test suite types.
message TestSuiteCommon {
  // A human-readable identifier for this test suite that will be consistent
  // between runs of the test plan generator.
  string display_name = 1;

  // The build target for this test unit.
  chromiumos.BuildTarget build_target = 2;

  // The build files provided to run this test unit.
  BuildPayload build_payload = 3;
}

message GceTestSuite {
  TestSuiteCommon common = 1;
  GceTestCfg gce = 2;
}

message HwTestSuite {
  TestSuiteCommon common = 1;
  HwTestCfg hw_test = 2;
}

message MoblabVmTestSuite {
  TestSuiteCommon common = 1;
  MoblabVmTestCfg moblab_vm = 2;
}

message TastVmTestSuite {
  TestSuiteCommon common = 1;
  TastVmTestCfg tast_vm = 2;
}

message VmTestSuite {
  TestSuiteCommon common = 1;
  VmTestCfg vm = 2;
}

