// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package testplans;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/testplans";

import "chromiumos/common.proto";
import "testplans/common.proto";

// Testing restrictions to apply to a source tree.
message TestRestriction {
  // Whether to disable hardware test suites.
  bool disable_hw_tests = 1;
  // Whether to disable virtual machine test suites.
  bool disable_vm_tests = 3;
  // Whether to disable non-Tast-based test suites.
  bool disable_non_tast_tests = 5;
  // A subset of build targets for which testing should be performed.
  // If this is nonempty, hw/vm tests will *only* be done for the provided
  // list of build targets.
  repeated chromiumos.BuildTarget only_test_build_targets = 4;
}

// A set of test restrictions for a source tree.
message SourceTreeTestRestriction {
  // A CrOS source tree.
  SourceTree source_tree = 1;
  // The test restrictions to apply to the source tree.
  TestRestriction test_restriction = 2;
}

// Configures test restrictions for all relevant source trees.
// This is the root message.
message SourceTreeTestCfg {
  // (Source tree, test restriction) pairs.
  repeated SourceTreeTestRestriction source_tree_test_restriction = 1;
}
