// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.config;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/config";

// Config defined configuration parameters of cros_test_platform.
message Config {
    // Swarming defines configuration parameters related to a swarming instance.
    message Swarming {
        string server = 1;

        string auth_json_path = 2;
    }

    // Isolate defines configuration parameters related to an isolate instance.
    message Isolate {
        string auth_json_path = 1;
    }

    // SkylabWorker defines configuration parameters related to
    // skylab_swarming_worker.
    message SkylabWorker {
        // LUCI project for tasks; e.g. "chromeos"
        string luci_project = 1;

        // LogDog host for test task logs, e.g. luci-logdog.appspot.com
        string log_dog_host = 2;
    }

    Swarming skylab_swarming = 1;

    Swarming autotest_proxy = 2;

    Isolate skylab_isolate = 3;

    SkylabWorker skylab_worker = 4;
}
