// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package test_platform.config;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/test_platform/config";

// Config defined configuration parameters of cros_test_platform.
message Config {
    // Swarming defines configuration parameters related to a swarming instance.
    message Swarming {
        string server = 1;

        string auth_json_path = 2;
    }

    // Isolate defines configuration parameters related to an isolate instance.
    message Isolate {
        string auth_json_path = 1;
    }

    // SkylabWorker defines configuration parameters related to
    // skylab_swarming_worker.
    message SkylabWorker {
        // LUCI project for tasks; e.g. "chromeos"
        string luci_project = 1;

        // LogDog host for test task logs, e.g. luci-logdog.appspot.com
        string log_dog_host = 2;
    }

    // AutotestBackend defines configuration parameters related to autotest
    // backend execution.
    message AutotestBackend {
        // afe_host is the hostname of the autotest frontend to be used for
        // autotest backend executions (e.g. cautotest or cautotest-staging).
        string afe_host = 1;
    }

    message SchedulerMigration {
        // gitiles_host is the host from which to fetch scheduler migration
        // config.
        string gitiles_host = 1;

        // git_project is the git project from which to fetch scheduler
        // migration config.
        string git_project = 2;

        // file_path is the file patch from which to fetch scheduler migration
        // config.
        string file_path = 3;

        // commitish is the git commitish from which to fetch scheduler
        // migration config.
        string commitish = 4;
    }

    // Versioning defines configuration parameters dictating which versions of
    // the downstream components to use.
    message Versioning {
        // CrosTestPlatformBinary describes which cros_test_platform version to
        // use.
        message CrosTestPlatformBinary {
            // Use the CIPD version with this label.
            string cipd_label = 1;
        }

        CrosTestPlatformBinary cros_test_platform_binary = 1;
    }

    Swarming skylab_swarming = 1;

    Swarming autotest_proxy = 2;

    Isolate skylab_isolate = 3;

    SkylabWorker skylab_worker = 4;

    AutotestBackend autotest_backend = 5;

    SchedulerMigration scheduler_migration = 6;

    Versioning versioning = 7;
}
