// Copyright 2025 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package auto_qual;

import "google/protobuf/descriptor.proto";
import "auto_qual/test_effort.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/auto_qual";

// Defines how to generate Test Efforts from LUCI Firmware Builders.
message BuilderQualConfig {
  // The name of the firmware builder.
  // This can be a SQL like pattern.
  //
  // Examples:
  //   * firmware-android-15949.B
  //   * firmware-android-brya-%
  string builder_name = 1;

  // A list of hardware models to generate qualification requests for.
  // The builder must generate firmware for the models specified here.
  // If this list is empty, then no models will be qualified.
  repeated string models = 2;

  // The operating systems to generate test efforts for.
  // If this list is empty, then no qualifications will be generated.
  repeated ModelTestEffortConfig.OsType operating_systems = 3;

  // Test Plan Type to use for the generated test efforts.
  ModelTestEffortConfig.TestPlan.TestPlanType test_plan_type = 4;

  // RO+RW or RW Test Effort.
  ModelTestEffortConfig.FirmwareType firmware_type = 5;

  // Test Effort type from enumerated type AP, EC, AP_EC
  ModelTestEffortConfig.TestEffortType test_effort_type = 6;
}

message BuilderQualConfigs {
  // Builder Qual Configs.
  repeated BuilderQualConfig builder_qual_config = 1;
}
