// Copyright 2025 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package auto_qual;

import "google/protobuf/descriptor.proto";
import "auto_qual/test.proto";

option go_package = "go.chromium.org/chromiumos/infra/proto/go/auto_qual";

// Config for testing of a specific model.
message ModelTestEffortConfig {

  enum FirmwareType {
    FIRMWARE_TYPE_UNSPECIFIED = 0;
    RO_RW = 1;
    RW = 2;
  }

  enum HardwareType {
    HARDWARE_TYPE_UNSPECIFIED = 0;
    EVT = 1;
    DVT = 2;
    PVT = 3;
    MP = 4;
  }

  enum OsType {
    OS_TYPE_UNSPECIFIED = 0;
    CROS = 1;
    AL = 2;
  }

  message TestPlan {
    reserved 2;

    enum TestPlanType {
      TEST_PLAN_TYPE_UNSPECIFIED = 0;
      FIRMWARE_ENABLED = 1;
      FIRMWARE_MEETS_KPI = 2;
      FIRMWARE_STRESSED = 3;
      FIRMWARE_QUAL = 4;
      FIRMWARE_LABQUAL = 5;
      FIRMWARE_ULDRENITE_CUSTOM = 6;
    }
    // Type of test to run
    TestPlanType type = 1;

    // Default Test Pool
    string test_pool = 3;

    // Default PD Test Pool
    string pd_test_pool = 4;

    // Tests to be excluded from the test effort
    repeated Test test_overrides = 5;
  }

  enum TestEffortType {
    TEST_EFFORT_TYPE_UNSPECIFIED = 0;
    AP = 1;
    EC = 2;
    AP_EC = 3;
  }

  message DeviceInfo {
    string model_name = 1;
    string sku = 2;
  }

  message FirmwareTestEffortVersion {
    uint32 major_version = 1;
    uint32 minor_version = 2;
    uint32 patch_number = 3;
    string uri = 4;
  }

  message GscTestEffortVersion {
    uint32 minor_version = 1;
    uint32 major_version = 2;
    uint32 epoch = 3;
  }

  message PreviousTestEffortVersion {
    FirmwareTestEffortVersion ap_version = 1;
    FirmwareTestEffortVersion ec_version = 2;
    repeated OsType os_test_effort_type = 3;
  }

  // Test Effort ID
  uint32 id = 1;

  // Test Effort Name
  string name = 2;

  // Board to be tested
  string board_name = 3;

  // Device to be tested
  repeated DeviceInfo devices = 4;

  // Branch to get firmware from
  string branch_name = 5;

  // Test Effort type from enumerated type AP, EC, AP_EC
  TestEffortType test_effort_type = 6;

  // RO or RW Test Effort
  FirmwareType firmware_type = 7;

  // HW phase in test
  HardwareType testing_hardware = 8;

  // Target milestone, to be used in test
  uint32 target_milestone_number = 9;

  // Primary AP RO FW Test Version
  FirmwareTestEffortVersion ap_ro_firmware_build_cros_test_effort_version = 10;

  // Primary AP RW FW Test Version
  FirmwareTestEffortVersion ap_rw_firmware_build_cros_test_effort_version = 11;

  // Primary EC RO FW Test Version
  FirmwareTestEffortVersion ec_ro_firmware_build_cros_test_effort_version = 12;

  // Primary EC RW FW Test Version
  FirmwareTestEffortVersion ec_rw_firmware_build_cros_test_effort_version = 13;

  // All Previous RO FW Versions to test for compatibility
  repeated PreviousTestEffortVersion ro_firmware_build_cros_versions = 14;

  // GSC Version to test with
  GscTestEffortVersion gsc_version = 15;

  // OS type
  repeated OsType os_test_effort_type = 16;

  // Test Plan
  repeated TestPlan test_plan = 17;

  // Max Test Retries
  uint32 max_retries = 18;

  // Latest RW FW Versions to test for compatibility
  PreviousTestEffortVersion latest_rw_firmware_versions = 19;
}

message ModelTestEffortConfigs {
  // Test Effort configs to be used
  repeated ModelTestEffortConfig test_efforts = 1;
}
