// Copyright 2025 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package auto_qual;

option go_package = "go.chromium.org/chromiumos/infra/proto/go/auto_qual";
import "auto_qual/test_effort.proto";
import "auto_qual/test.proto";

message TestPlan {
  repeated ModelTestEffortConfig.OsType os = 1;
  ModelTestEffortConfig.TestPlan.TestPlanType test_effort = 2;
  repeated Test test = 3;
}

message TestPlans { repeated TestPlan test_plan = 1; }
