// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/artifacts.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An artifact is a file generated during or after a build.
type Artifact struct {
	// Absolute path to the artifact file.
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Artifact) Reset()         { *m = Artifact{} }
func (m *Artifact) String() string { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()    {}
func (*Artifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a7d4c8524262a7, []int{0}
}

func (m *Artifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artifact.Unmarshal(m, b)
}
func (m *Artifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artifact.Marshal(b, m, deterministic)
}
func (m *Artifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artifact.Merge(m, src)
}
func (m *Artifact) XXX_Size() int {
	return xxx_messageInfo_Artifact.Size(m)
}
func (m *Artifact) XXX_DiscardUnknown() {
	xxx_messageInfo_Artifact.DiscardUnknown(m)
}

var xxx_messageInfo_Artifact proto.InternalMessageInfo

func (m *Artifact) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Request describing where build artifact bundles for a given build target
// should be dumped.
type BundleRequest struct {
	// The build target to bundle artifacts for.
	// Deprecated. Use sysroot instead.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// Absolute path to the directory in which artifacts should be dropped.
	OutputDir string `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	// The chroot where the sysroot lives.
	Chroot *chromiumos.Chroot `protobuf:"bytes,3,opt,name=chroot,proto3" json:"chroot,omitempty"`
	// The sysroot where the files live.
	Sysroot              *Sysroot `protobuf:"bytes,4,opt,name=sysroot,proto3" json:"sysroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleRequest) Reset()         { *m = BundleRequest{} }
func (m *BundleRequest) String() string { return proto.CompactTextString(m) }
func (*BundleRequest) ProtoMessage()    {}
func (*BundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a7d4c8524262a7, []int{1}
}

func (m *BundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleRequest.Unmarshal(m, b)
}
func (m *BundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleRequest.Marshal(b, m, deterministic)
}
func (m *BundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleRequest.Merge(m, src)
}
func (m *BundleRequest) XXX_Size() int {
	return xxx_messageInfo_BundleRequest.Size(m)
}
func (m *BundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BundleRequest proto.InternalMessageInfo

func (m *BundleRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *BundleRequest) GetOutputDir() string {
	if m != nil {
		return m.OutputDir
	}
	return ""
}

func (m *BundleRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

func (m *BundleRequest) GetSysroot() *Sysroot {
	if m != nil {
		return m.Sysroot
	}
	return nil
}

// Response describing which bundles were dumped to the given output directory.
type BundleResponse struct {
	// The artifacts that added to the output directory.
	Artifacts            []*Artifact `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BundleResponse) Reset()         { *m = BundleResponse{} }
func (m *BundleResponse) String() string { return proto.CompactTextString(m) }
func (*BundleResponse) ProtoMessage()    {}
func (*BundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a7d4c8524262a7, []int{2}
}

func (m *BundleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleResponse.Unmarshal(m, b)
}
func (m *BundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleResponse.Marshal(b, m, deterministic)
}
func (m *BundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleResponse.Merge(m, src)
}
func (m *BundleResponse) XXX_Size() int {
	return xxx_messageInfo_BundleResponse.Size(m)
}
func (m *BundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BundleResponse proto.InternalMessageInfo

func (m *BundleResponse) GetArtifacts() []*Artifact {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

// Request describing where to find build artifacts that are taken from a
// sysroot.
type BundleVmFilesRequest struct {
	// The chroot where the sysroot lives.
	Chroot *chromiumos.Chroot `protobuf:"bytes,1,opt,name=chroot,proto3" json:"chroot,omitempty"`
	// The sysroot where the files live.
	Sysroot *Sysroot `protobuf:"bytes,2,opt,name=sysroot,proto3" json:"sysroot,omitempty"`
	// Test results directory relative to the sysroot.
	TestResultsDir string `protobuf:"bytes,3,opt,name=test_results_dir,json=testResultsDir,proto3" json:"test_results_dir,omitempty"`
	// Absolute path to the directory in which artifacts should be dropped.
	OutputDir            string   `protobuf:"bytes,4,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleVmFilesRequest) Reset()         { *m = BundleVmFilesRequest{} }
func (m *BundleVmFilesRequest) String() string { return proto.CompactTextString(m) }
func (*BundleVmFilesRequest) ProtoMessage()    {}
func (*BundleVmFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a7d4c8524262a7, []int{3}
}

func (m *BundleVmFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleVmFilesRequest.Unmarshal(m, b)
}
func (m *BundleVmFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleVmFilesRequest.Marshal(b, m, deterministic)
}
func (m *BundleVmFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleVmFilesRequest.Merge(m, src)
}
func (m *BundleVmFilesRequest) XXX_Size() int {
	return xxx_messageInfo_BundleVmFilesRequest.Size(m)
}
func (m *BundleVmFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleVmFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BundleVmFilesRequest proto.InternalMessageInfo

func (m *BundleVmFilesRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

func (m *BundleVmFilesRequest) GetSysroot() *Sysroot {
	if m != nil {
		return m.Sysroot
	}
	return nil
}

func (m *BundleVmFilesRequest) GetTestResultsDir() string {
	if m != nil {
		return m.TestResultsDir
	}
	return ""
}

func (m *BundleVmFilesRequest) GetOutputDir() string {
	if m != nil {
		return m.OutputDir
	}
	return ""
}

// Request describing where to find Chrome orderfile artifacts
type BundleChromeOrderfileRequest struct {
	// The chroot where the orderfile lives.
	Chroot *chromiumos.Chroot `protobuf:"bytes,1,opt,name=chroot,proto3" json:"chroot,omitempty"`
	// The build_target of the builder.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// The Chrome version that builder uses
	ChromeVersion string `protobuf:"bytes,3,opt,name=chrome_version,json=chromeVersion,proto3" json:"chrome_version,omitempty"`
	// Absolute path to the directory in which artifacts should be dropped.
	OutputDir            string   `protobuf:"bytes,4,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleChromeOrderfileRequest) Reset()         { *m = BundleChromeOrderfileRequest{} }
func (m *BundleChromeOrderfileRequest) String() string { return proto.CompactTextString(m) }
func (*BundleChromeOrderfileRequest) ProtoMessage()    {}
func (*BundleChromeOrderfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a7d4c8524262a7, []int{4}
}

func (m *BundleChromeOrderfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleChromeOrderfileRequest.Unmarshal(m, b)
}
func (m *BundleChromeOrderfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleChromeOrderfileRequest.Marshal(b, m, deterministic)
}
func (m *BundleChromeOrderfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleChromeOrderfileRequest.Merge(m, src)
}
func (m *BundleChromeOrderfileRequest) XXX_Size() int {
	return xxx_messageInfo_BundleChromeOrderfileRequest.Size(m)
}
func (m *BundleChromeOrderfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleChromeOrderfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BundleChromeOrderfileRequest proto.InternalMessageInfo

func (m *BundleChromeOrderfileRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

func (m *BundleChromeOrderfileRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *BundleChromeOrderfileRequest) GetChromeVersion() string {
	if m != nil {
		return m.ChromeVersion
	}
	return ""
}

func (m *BundleChromeOrderfileRequest) GetOutputDir() string {
	if m != nil {
		return m.OutputDir
	}
	return ""
}

func init() {
	proto.RegisterType((*Artifact)(nil), "chromite.api.Artifact")
	proto.RegisterType((*BundleRequest)(nil), "chromite.api.BundleRequest")
	proto.RegisterType((*BundleResponse)(nil), "chromite.api.BundleResponse")
	proto.RegisterType((*BundleVmFilesRequest)(nil), "chromite.api.BundleVmFilesRequest")
	proto.RegisterType((*BundleChromeOrderfileRequest)(nil), "chromite.api.BundleChromeOrderfileRequest")
}

func init() { proto.RegisterFile("chromite/api/artifacts.proto", fileDescriptor_62a7d4c8524262a7) }

var fileDescriptor_62a7d4c8524262a7 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0x2a, 0x90, 0x49, 0x13, 0xc2, 0xf2, 0x11, 0xcb, 0x0d, 0xa8, 0xb2, 0x84, 0x14,
	0xf5, 0x60, 0x4b, 0x01, 0x21, 0xc4, 0xad, 0x01, 0x52, 0x21, 0x8a, 0x08, 0x4e, 0x5a, 0xa1, 0x5e,
	0xa2, 0x4d, 0xbc, 0x71, 0x57, 0x8a, 0xbd, 0x66, 0x77, 0x5d, 0xd4, 0xff, 0xc6, 0x89, 0x0b, 0x17,
	0xfe, 0x0a, 0x77, 0x8e, 0xc8, 0xbb, 0x76, 0x1c, 0x57, 0x11, 0x25, 0x4a, 0x6f, 0xc9, 0x7b, 0xe3,
	0x37, 0x33, 0x6f, 0x66, 0x77, 0xa1, 0x33, 0xbb, 0xe0, 0x2c, 0xa4, 0x92, 0xb8, 0x38, 0xa6, 0x2e,
	0xe6, 0x92, 0xce, 0xf1, 0x4c, 0x0a, 0x27, 0xe6, 0x4c, 0x32, 0xb4, 0x97, 0xb3, 0x0e, 0x8e, 0xa9,
	0x55, 0x8e, 0x9d, 0x26, 0x74, 0xe1, 0x4f, 0x70, 0x4c, 0x75, 0xac, 0x65, 0x95, 0x58, 0x71, 0x25,
	0x38, 0x63, 0x32, 0xe3, 0xda, 0x9a, 0x4b, 0x42, 0x26, 0xdc, 0x19, 0x0b, 0x43, 0x16, 0x69, 0xc2,
	0x7e, 0x0a, 0x77, 0x8f, 0xb2, 0x9c, 0x08, 0xc1, 0x6e, 0x8c, 0xe5, 0x85, 0x69, 0x1c, 0x18, 0xdd,
	0x9a, 0xa7, 0x7e, 0xdb, 0x3f, 0x0d, 0x68, 0xf4, 0x93, 0xc8, 0x5f, 0x10, 0x8f, 0x7c, 0x4d, 0x88,
	0x90, 0xe8, 0x35, 0xec, 0xe9, 0xcc, 0x12, 0xf3, 0x80, 0x48, 0x15, 0x5d, 0xef, 0xb5, 0x9d, 0x22,
	0x83, 0xd3, 0x4f, 0xf9, 0xb1, 0xa2, 0xbd, 0xfa, 0xb4, 0xf8, 0x83, 0x9e, 0x00, 0xb0, 0x44, 0xc6,
	0x89, 0x9c, 0xf8, 0x94, 0x9b, 0x15, 0x95, 0xa7, 0xa6, 0x91, 0xb7, 0x94, 0xa3, 0x43, 0xa8, 0xa6,
	0x2a, 0x4c, 0x9a, 0x3b, 0x4a, 0x14, 0xad, 0x8a, 0xbe, 0x51, 0x8c, 0x97, 0x45, 0x20, 0x17, 0xee,
	0x64, 0x2d, 0x9a, 0xbb, 0x2a, 0xf8, 0x91, 0xb3, 0xea, 0x95, 0x33, 0xd2, 0xa4, 0x97, 0x47, 0xd9,
	0x03, 0x68, 0xe6, 0x8d, 0x88, 0x98, 0x45, 0x82, 0xa0, 0x17, 0x50, 0x5b, 0xfa, 0x6d, 0x1a, 0x07,
	0x3b, 0xdd, 0x7a, 0xef, 0x71, 0x59, 0x24, 0xb7, 0xc6, 0x2b, 0x02, 0xed, 0xef, 0x06, 0x3c, 0xd4,
	0x42, 0x67, 0xe1, 0x80, 0x2e, 0x88, 0xc8, 0x8d, 0x29, 0xaa, 0x37, 0x36, 0xa9, 0xbe, 0xf2, 0x3f,
	0xd5, 0xa3, 0x2e, 0xb4, 0x24, 0x11, 0x72, 0xc2, 0x89, 0x48, 0x16, 0x52, 0x28, 0xff, 0x76, 0x94,
	0x7f, 0xcd, 0x14, 0xf7, 0x34, 0x9c, 0x9a, 0x58, 0xf6, 0x78, 0xf7, 0x9a, 0xc7, 0xf6, 0x2f, 0x03,
	0x3a, 0xba, 0xfc, 0xb4, 0xa4, 0x90, 0x7c, 0xe2, 0x3e, 0xe1, 0x73, 0x5a, 0xcc, 0x77, 0x93, 0x36,
	0xae, 0xef, 0x42, 0x65, 0x83, 0x5d, 0x78, 0x06, 0x4d, 0x15, 0x46, 0x26, 0x97, 0x84, 0x0b, 0xca,
	0xa2, 0xac, 0x9f, 0x86, 0x46, 0xcf, 0x34, 0x78, 0x43, 0x3b, 0xbd, 0x3f, 0x55, 0x68, 0xe5, 0x53,
	0x12, 0x23, 0xc2, 0x2f, 0xe9, 0x8c, 0xa0, 0x21, 0x3c, 0xd0, 0x2d, 0x1e, 0x25, 0x92, 0xa5, 0xf6,
	0xa8, 0x39, 0xa1, 0xfd, 0xb2, 0xc7, 0xa5, 0xb5, 0xb6, 0x3a, 0xeb, 0xc9, 0x6c, 0x55, 0x3e, 0x42,
	0x4b, 0x23, 0xef, 0x54, 0x0b, 0x27, 0x2c, 0xd8, 0x4a, 0xee, 0x43, 0xbe, 0x8b, 0x03, 0xca, 0xc3,
	0x6f, 0x98, 0x93, 0x5b, 0x11, 0x7b, 0x1f, 0xe2, 0x80, 0x9c, 0xd3, 0x78, 0x1b, 0xb1, 0x31, 0xb4,
	0x35, 0x32, 0xa4, 0x51, 0x44, 0xfc, 0xe3, 0xf4, 0x13, 0xa5, 0xbb, 0x55, 0xbf, 0x5f, 0x60, 0x5f,
	0x23, 0x23, 0x1a, 0xc6, 0xf9, 0xe6, 0x2d, 0xc7, 0xb6, 0x8d, 0xf2, 0x09, 0xdc, 0xd3, 0xc8, 0x18,
	0xdf, 0xc2, 0x98, 0x4f, 0xc1, 0xcc, 0xd4, 0x88, 0x90, 0xa7, 0xb1, 0x8f, 0x25, 0x19, 0xe2, 0xab,
	0x05, 0xc3, 0xfe, 0x56, 0xb2, 0x9f, 0xf3, 0x3b, 0x34, 0xbb, 0x31, 0x90, 0xbd, 0x2e, 0xbc, 0x7c,
	0x9d, 0xdc, 0x20, 0x19, 0x81, 0xad, 0x91, 0xe5, 0xf9, 0x3d, 0x26, 0x11, 0xe1, 0x58, 0x52, 0x16,
	0x15, 0xc6, 0x1e, 0xae, 0xd3, 0x58, 0x7f, 0xee, 0xff, 0x9d, 0xcf, 0xba, 0xff, 0xe3, 0xb7, 0xd5,
	0x58, 0xb9, 0x2f, 0x5b, 0x95, 0xfe, 0xab, 0xf3, 0x97, 0x01, 0x5b, 0x1e, 0x75, 0x87, 0xf1, 0xc0,
	0x5d, 0x79, 0x65, 0x68, 0x34, 0xe7, 0xd8, 0x55, 0x8f, 0x8c, 0x1b, 0x30, 0x77, 0xf5, 0x6d, 0x9a,
	0x56, 0x15, 0xfc, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0xb7, 0x77, 0xc1, 0xfc, 0x06,
	0x00, 0x00,
}
