// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.1
// source: chromite/api/ide.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdeServiceClient is the client API for IdeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdeServiceClient interface {
	// Generate compilation database for ChromeOS packages and
	// merge build artifacts for selected packages and their dependencies
	// into a single build directory.
	GenerateMergedCompilationDB(ctx context.Context, in *GenerateMergedCompilationDBRequest, opts ...grpc.CallOption) (*GenerateMergedCompilationDBResponse, error)
}

type ideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdeServiceClient(cc grpc.ClientConnInterface) IdeServiceClient {
	return &ideServiceClient{cc}
}

func (c *ideServiceClient) GenerateMergedCompilationDB(ctx context.Context, in *GenerateMergedCompilationDBRequest, opts ...grpc.CallOption) (*GenerateMergedCompilationDBResponse, error) {
	out := new(GenerateMergedCompilationDBResponse)
	err := c.cc.Invoke(ctx, "/chromite.api.IdeService/GenerateMergedCompilationDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdeServiceServer is the server API for IdeService service.
// All implementations must embed UnimplementedIdeServiceServer
// for forward compatibility
type IdeServiceServer interface {
	// Generate compilation database for ChromeOS packages and
	// merge build artifacts for selected packages and their dependencies
	// into a single build directory.
	GenerateMergedCompilationDB(context.Context, *GenerateMergedCompilationDBRequest) (*GenerateMergedCompilationDBResponse, error)
	mustEmbedUnimplementedIdeServiceServer()
}

// UnimplementedIdeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdeServiceServer struct {
}

func (UnimplementedIdeServiceServer) GenerateMergedCompilationDB(context.Context, *GenerateMergedCompilationDBRequest) (*GenerateMergedCompilationDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMergedCompilationDB not implemented")
}
func (UnimplementedIdeServiceServer) mustEmbedUnimplementedIdeServiceServer() {}

// UnsafeIdeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdeServiceServer will
// result in compilation errors.
type UnsafeIdeServiceServer interface {
	mustEmbedUnimplementedIdeServiceServer()
}

func RegisterIdeServiceServer(s grpc.ServiceRegistrar, srv IdeServiceServer) {
	s.RegisterService(&IdeService_ServiceDesc, srv)
}

func _IdeService_GenerateMergedCompilationDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMergedCompilationDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdeServiceServer).GenerateMergedCompilationDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromite.api.IdeService/GenerateMergedCompilationDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdeServiceServer).GenerateMergedCompilationDB(ctx, req.(*GenerateMergedCompilationDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdeService_ServiceDesc is the grpc.ServiceDesc for IdeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chromite.api.IdeService",
	HandlerType: (*IdeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMergedCompilationDB",
			Handler:    _IdeService_GenerateMergedCompilationDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chromite/api/ide.proto",
}
