// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/toolchain.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateChromeEbuildRequest struct {
	BuildTarget          *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateChromeEbuildRequest) Reset()         { *m = UpdateChromeEbuildRequest{} }
func (m *UpdateChromeEbuildRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateChromeEbuildRequest) ProtoMessage()    {}
func (*UpdateChromeEbuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff43bdb7436d394, []int{0}
}

func (m *UpdateChromeEbuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChromeEbuildRequest.Unmarshal(m, b)
}
func (m *UpdateChromeEbuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChromeEbuildRequest.Marshal(b, m, deterministic)
}
func (m *UpdateChromeEbuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChromeEbuildRequest.Merge(m, src)
}
func (m *UpdateChromeEbuildRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateChromeEbuildRequest.Size(m)
}
func (m *UpdateChromeEbuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChromeEbuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChromeEbuildRequest proto.InternalMessageInfo

func (m *UpdateChromeEbuildRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

type UpdateChromeEbuildResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateChromeEbuildResponse) Reset()         { *m = UpdateChromeEbuildResponse{} }
func (m *UpdateChromeEbuildResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateChromeEbuildResponse) ProtoMessage()    {}
func (*UpdateChromeEbuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff43bdb7436d394, []int{1}
}

func (m *UpdateChromeEbuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChromeEbuildResponse.Unmarshal(m, b)
}
func (m *UpdateChromeEbuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChromeEbuildResponse.Marshal(b, m, deterministic)
}
func (m *UpdateChromeEbuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChromeEbuildResponse.Merge(m, src)
}
func (m *UpdateChromeEbuildResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateChromeEbuildResponse.Size(m)
}
func (m *UpdateChromeEbuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChromeEbuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChromeEbuildResponse proto.InternalMessageInfo

type UploadVettedOrderfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVettedOrderfileRequest) Reset()         { *m = UploadVettedOrderfileRequest{} }
func (m *UploadVettedOrderfileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadVettedOrderfileRequest) ProtoMessage()    {}
func (*UploadVettedOrderfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff43bdb7436d394, []int{2}
}

func (m *UploadVettedOrderfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVettedOrderfileRequest.Unmarshal(m, b)
}
func (m *UploadVettedOrderfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVettedOrderfileRequest.Marshal(b, m, deterministic)
}
func (m *UploadVettedOrderfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVettedOrderfileRequest.Merge(m, src)
}
func (m *UploadVettedOrderfileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadVettedOrderfileRequest.Size(m)
}
func (m *UploadVettedOrderfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVettedOrderfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVettedOrderfileRequest proto.InternalMessageInfo

type UploadVettedOrderfileResponse struct {
	// Status of the service
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVettedOrderfileResponse) Reset()         { *m = UploadVettedOrderfileResponse{} }
func (m *UploadVettedOrderfileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadVettedOrderfileResponse) ProtoMessage()    {}
func (*UploadVettedOrderfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ff43bdb7436d394, []int{3}
}

func (m *UploadVettedOrderfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVettedOrderfileResponse.Unmarshal(m, b)
}
func (m *UploadVettedOrderfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVettedOrderfileResponse.Marshal(b, m, deterministic)
}
func (m *UploadVettedOrderfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVettedOrderfileResponse.Merge(m, src)
}
func (m *UploadVettedOrderfileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadVettedOrderfileResponse.Size(m)
}
func (m *UploadVettedOrderfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVettedOrderfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVettedOrderfileResponse proto.InternalMessageInfo

func (m *UploadVettedOrderfileResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*UpdateChromeEbuildRequest)(nil), "chromite.api.UpdateChromeEbuildRequest")
	proto.RegisterType((*UpdateChromeEbuildResponse)(nil), "chromite.api.UpdateChromeEbuildResponse")
	proto.RegisterType((*UploadVettedOrderfileRequest)(nil), "chromite.api.UploadVettedOrderfileRequest")
	proto.RegisterType((*UploadVettedOrderfileResponse)(nil), "chromite.api.UploadVettedOrderfileResponse")
}

func init() { proto.RegisterFile("chromite/api/toolchain.proto", fileDescriptor_7ff43bdb7436d394) }

var fileDescriptor_7ff43bdb7436d394 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0xe9, 0x7f, 0x51, 0xfe, 0x4e, 0x2b, 0xd4, 0x01, 0xad, 0x0e, 0xf5, 0x83, 0x6c, 0x2c,
	0x0a, 0x33, 0x50, 0x41, 0xc5, 0x65, 0xc5, 0xb5, 0x50, 0x5b, 0x0b, 0x6e, 0x64, 0x9a, 0xdc, 0xa6,
	0x03, 0x49, 0xef, 0x38, 0x73, 0xe3, 0x5b, 0xf8, 0x52, 0xbe, 0x8f, 0xef, 0x20, 0x4d, 0xd2, 0x0f,
	0xb5, 0x45, 0x97, 0x37, 0xe7, 0xe4, 0x77, 0x6f, 0x4e, 0x0e, 0x6b, 0x85, 0x13, 0x87, 0xa9, 0x21,
	0x50, 0xda, 0x1a, 0x45, 0x88, 0x49, 0x38, 0xd1, 0x66, 0x2a, 0xad, 0x43, 0x42, 0x5e, 0x9f, 0xab,
	0x52, 0x5b, 0x23, 0xbe, 0x7a, 0x47, 0x99, 0x49, 0xa2, 0x67, 0x6d, 0x4d, 0xe1, 0x15, 0xcd, 0x42,
	0xcd, 0x52, 0xf4, 0x2a, 0xc4, 0x34, 0xc5, 0x12, 0x12, 0x0c, 0xd9, 0xc1, 0xc0, 0x46, 0x9a, 0xe0,
	0x76, 0x66, 0x80, 0xbb, 0xfc, 0xc5, 0x1e, 0xbc, 0x64, 0xe0, 0x89, 0xdf, 0xb0, 0x7a, 0x01, 0x22,
	0xed, 0x62, 0xa0, 0xfd, 0xca, 0x49, 0xa5, 0x5d, 0xeb, 0x34, 0xe5, 0x12, 0x26, 0xbb, 0x33, 0xbd,
	0x9f, 0xcb, 0xbd, 0xda, 0x68, 0x39, 0x04, 0x2d, 0x26, 0xd6, 0x81, 0xbd, 0xc5, 0xa9, 0x87, 0xe0,
	0x88, 0xb5, 0x06, 0x36, 0x41, 0x1d, 0x3d, 0x02, 0x11, 0x44, 0xf7, 0x2e, 0x02, 0x37, 0x36, 0x09,
	0x94, 0x9b, 0x83, 0x2b, 0x76, 0xb8, 0x41, 0x2f, 0x00, 0x7c, 0x8f, 0x55, 0x3d, 0x69, 0xca, 0x7c,
	0x7e, 0xd4, 0xff, 0x5e, 0x39, 0x75, 0xde, 0xfe, 0xb1, 0x46, 0x7f, 0x1e, 0xd4, 0x03, 0xb8, 0x57,
	0x13, 0x02, 0x27, 0x76, 0xfc, 0xf3, 0x96, 0xa1, 0xa1, 0xc9, 0x82, 0xcb, 0x4f, 0xe5, 0x6a, 0x9a,
	0x72, 0x63, 0x26, 0xa2, 0xfd, 0xbb, 0xb1, 0x3c, 0xd1, 0xb2, 0xdd, 0xb5, 0xdf, 0xc0, 0xcf, 0xbe,
	0x23, 0x36, 0x07, 0x21, 0xce, 0xff, 0xe4, 0x2d, 0x36, 0x8a, 0x9d, 0xf7, 0x0f, 0xb1, 0xcd, 0xb6,
	0x16, 0x45, 0x69, 0x54, 0xba, 0xd7, 0x4f, 0x97, 0x31, 0x2e, 0x7e, 0x98, 0x44, 0x17, 0xab, 0x95,
	0x2a, 0x98, 0xe9, 0xd8, 0x69, 0x95, 0x37, 0x41, 0xc5, 0xa8, 0x56, 0x2b, 0x34, 0xaa, 0xe6, 0x8f,
	0x2f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x58, 0x8d, 0xd3, 0x85, 0x02, 0x00, 0x00,
}
